canonical/apport

tests/system/test_unkillable_shutdown.py
The test case `test_omit_all_processes_except_one` is racy and fails sometimes:
```
test_omit_all_processes_except_one (tests.system.test_unkillable_shutdown.TestUnkillableShutdown)
unkillable_shutdown will write exactly one report. ... Running as unit: run-r0b0d3fe87473410c9eb61a5ae4635938.service
FAIL
FAIL: test_omit_all_processes_except_one (tests.system.test_unkillable_shutdown.TestUnkillableShutdown)
unkillable_shutdown will write exactly one report.
File "tests/system/test_unkillable_shutdown.py", line 96, in test_omit_all_processes_except_one
pid = self._launch_process_with_different_session_id(existing_pids) …
```
=> tests: Wait for test process to be started

tests/integration/test_signal_crashes.py
`test_crash_setuid_unpackaged` is racy and rarely fails with:
```
ERROR: test_crash_setuid_unpackaged (tests.integration.test_signal_crashes.T)
report generation for unpackaged setuid program
File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1661, in wrapper
return fun(self, *args, **kwargs)
File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1782, in cmdline
data = f.read()
ProcessLookupError: [Errno 3] No such process
During handling of the above exception, another exception occurred:
File "tests/integration/test_signal_crashes.py", line 746, in …
```
=> tests: Fix psutil.NoSuchProcess in wait_for_gdb_child_process

tests/helper.py, tests/integration/test_apport_valgrind.py, tests/integration/test_java_crashes.py, tests/integration/test_packaging_apt_dpkg.py, tests/integration/test_packaging_rpm.py, tests/integration/test_report.py, tests/system/test_apport_valgrind.py, tests/system/test_packaging_apt_dpkg.py, tests/system/test_signal_crashes.py
Add a `skip_if_command_is_missing` helper function to make the skip code line shorter.
=> tests: Add skip_if_command_is_missing helper function

apport/report.py, bin/apport-valgrind, tests/integration/test_apport_valgrind.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py
With the new Ubuntu debuginfod
service (https://debuginfod.ubuntu.com), and with the prospect of
having the system automatically fetch debuginfo from the internet
without user intervention, it is necessary to adjust apport to cope
with this scenario.
I had a conversation with bdmurray and he was concerned that having a
debuginfod-enabled GDB generate the corefiles that are eventually
submitted to Ubuntu can be a problem.
This commit disables GDB's debuginfod support when collecting a
report.  I chose not to touch GDB's settings on apport-retrace because
I think we should honour the user choice there.
Bug: https://launchpad.net/bugs/1989803
=> Disable debuginfod when collecting a report

bin/apport-cli, tests/integration/test_ui_cli.py
apport-cli fails when viewing the crash report:
```
File "bin/apport-cli", line 187, in ui_update_view
subprocess.run(
File "/usr/lib/python3.10/subprocess.py", line 501, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/lib/python3.10/subprocess.py", line 835, in __init__
errread, errwrite) = self._get_handles(stdin, stdout, stderr)
File "/usr/lib/python3.10/subprocess.py", line 1606, in _get_handles
p2cread = stdin.fileno()
AttributeError: 'bytes' object has no attribute 'fileno'
```
The `stdin` parameter for `subprocess.run` must be an existing file descriptor or an existing file object with a valid file descriptor. Use the `input` for byte sequences.
Bug: https://launchpad.net/bugs/1991200
Fixes: 9340a43dd934 ("Use subprocess.run instead …
=> apport-cli: Fix AttributeError: 'bytes' object has no attribute 'fileno'

apport/ui.py
```
apport/ui.py:971: error: Incompatible types in assignment (expression has type "bool", variable has type "Union[_SUPPRESS_T, str]")
```
The `help` parameter for `add_argument` takes `Optional[Text]`. Therefore set `suppress` to `None` if the help should not be suppressed.
=> Fix mypy for 'suppress' in apport/ui.py

apport/ui.py, bin/apport-cli, gtk/apport-gtk, kde/apport-kde, tests/integration/test_ui.py, tests/integration/test_ui_cli.py, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py
The UI test cases need to save `sys.argv` and set them for testing. Instead of fiddling around with `sys.argv`, pass around the command line arguments and `argv` parameter. For `apport-kde` determine the UI data path once and pass it around as `ui_data_path`.
=> Pass around command line arguments to ease testing

bin/apport-bug
On LXQt `apport-bug` is unable to open the Firefox snap at the very end of the process:
```
$ env -i apport-bug apport
[...]
Choices:
1: Launch a browser now
C: Cancel
Please choose (1/C): 1
/usr/bin/xdg-open: 882: firefox: not found
/usr/bin/xdg-open: 882: firefox: not found
xdg-open: no method available for opening 'https://bugs.launchpad.net/ubuntu/+source/apport/+filebug/d7ffa3e0-d46d-11ec-a167-40a8f03099c8?'
```
The Firefox snap provides `/snap/bin/firefox`. `apport-bug` sets the environment variable `PATH`, but does not include `/snap/bin`:
```
$ PATH=/usr/sbin:/usr/bin:/sbin:/bin xdg-open https://ubuntu.com
/usr/bin/xdg-open: 882: firefox: not found
/usr/bin/xdg-open: 882: firefox: not found
xdg-open: no method available for opening 'https://ubuntu.com'
```
`xdg-open` behaves …
=> apport-bug: Add /snap/bin to PATH for Firefox snap

NEWS.md, apport/ui.py
Release apport 2.23.1.
This is a draft, but `NEWS.md` can already be reviewed.
=> Release apport 2.23.1

README.md
Document how to create releases.
Is it okay to add it to `README.md` or better put it somewhere else?
=> README.md: Document how to create releases

tests/system/test_ui_kde.py
The KDE test cases wait for dialogs to appear and then interact with them. In case they do not appear after a short time period, more time will be waited and retried. This "waiting additional time" is not triggered on every CI run and therefore the code coverage varies.
Do not cover this retry test code to stabilize the test coverage report.
=> tests: Do not cover potential unused retry test code

.github/workflows/ci.yaml
Installing Apport with layout `deb` and prefix `/usr` installs the `etc` directory into the local directory instead of `/`.
Set `--root` to `/` to install all files into the system.
Remove system installed Apport to avoid mixing the Apport version to test and the system installed Apport.
=> CI: Remove system installed Apport

.github/workflows/ci.yaml, tests/integration/test_ui.py, tests/integration/test_ui_cli.py
Running the CLI UI tests against the install Apport fails:
```
[...]
File "tests/integration/test_ui_cli.py", line 25, in <module>
apport_cli = import_module_from_file(apport_cli_path)
File "tests/helper.py", line 48, in import_module_from_file
spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 879, in exec_module
File "<frozen importlib._bootstrap_external>", line 1016, in get_code
File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/apport/apport-cli'
```
The CLI is installed in `/usr/bin/apport-cli`.
The UI integration test case `test_run_crash_kernel` fails on Azure:
```
>       self.assertEqual(
self.ui.opened_url, …
```
=> tests: Fix path for installed apport-cli and fix test_run_crash_kernel on Azure

tests/system/test_ui_gtk.py
The GTK test cases wait for dialogs to appear and then interact with them. In case they do not appear after a short time period, more time will be waited and retried. This "waiting additional time" is not triggered on every CI run and therefore the code coverage varies.
Do not cover this retry test code to stabilize the test coverage report.
=> tests: Do not cover potential unused retry test code in GTK

tests/integration/test_ui.py
The autopkgtest for apport 2.23.1-0ubuntu1 fails on ppc64el:
```
FAIL: test_run_crash_kernel (tests.integration.test_ui.T)
run_crash() for a kernel error
File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
return func(*newargs, **newkeywargs)
File "tests/integration/test_ui.py", line 1617, in test_run_crash_kernel
self.assertEqual(
AssertionError: 'http://linux.bugs.example.com/5' != 'http://linux-signed.bugs.example.com/5'
- http://linux.bugs.example.com/5
+ http://linux-signed.bugs.example.com/5
? +++++++
```
Sometimes the Linux …
=> tests: Determine source package dynamically in test_run_crash_kernel

.github/workflows/ci.yaml
GitHub CI shows following warning: "Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, codecov/codecov-action, actions/checkout"
=> CI: Upgrade to actions/checkout@v3 and codecov/codecov-action@v3

apport/packaging.py, bin/apport-cli, setup.py, tests/helper.py
pylint 2.15.5 complains:
```
************* Module apport.packaging_impl.apt_dpkg
apport/packaging_impl/apt_dpkg.py:248:4: W0221: Number of parameters was 1 in 'PackageInfo.is_native_origin_package' and is now 2 in overridden '__AptDpkgPackageInfo.is_native_origin_package' method (arguments-differ)
apport/packaging_impl/apt_dpkg.py:450:4: W0221: Number of parameters was 1 in 'PackageInfo.get_modified_conffiles' and is now 2 in overridden '__AptDpkgPackageInfo.get_modified_conffiles' method (arguments-differ)
apport/packaging_impl/apt_dpkg.py:580:4: W0221: Number of parameters was 1 in 'PackageInfo.get_system_architecture' and is now 0 in overridden '__AptDpkgPackageInfo.get_system_architecture' method (arguments-differ)
apport/packaging_impl/apt_dpkg.py:592:4: W0221: Number of parameters …
```
=> fix: Address complaints from pylint 2.15.5

bin/apport-unpack, tests/integration/test_apport_unpack.py
Refactor `apport-unpack` and its test suite to avoid code duplication and making fixing https://launchpad.net/bugs/1996040 easier.
=> Refactor apport-unpack

bin/apport-unpack, data/whoopsie-upload-all, problem_report.py, tests/integration/test_apport_unpack.py, tests/integration/test_whoopsie_upload_all.py, tests/unit/test_problem_report.py
When passing a core file, `apport-unpack` will crash:
```
File "bin/apport-unpack", line 91, in <module>
main()
File "bin/apport-unpack", line 67, in main
pr = load_report(args.report)
File "bin/apport-unpack", line 47, in load_report
pr.load(f, binary=False)
File "problem_report.py", line 167, in load
key = key.decode("ASCII")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 2: ordinal not in range(128)
```
Wrap `UnicodeDecodeError` in a `MalformedProblemReport` exception and catch this exception in `apport-unpack` to print nice error message.
Please review and merge the refactoring in #23 first.
Bug-Ubuntu: https://launchpad.net/bugs/1996040
=> fix: Catch malformed problem report

problem_report.py, tests/unit/test_problem_report.py
The problem report might be malformed which lets `whoopsie-upload-all` crash:
```
  File "data/whoopsie-upload-all", line 250, in <module>
    main()
  File "data/whoopsie-upload-all", line 232, in main
    stamps = collect_info()
  File "data/whoopsie-upload-all", line 163, in collect_info
    res = process_report(r)
  File "data/whoopsie-upload-all", line 77, in process_report
    r.load(f, binary="compressed")
  File "problem_report.py", line 173, in load
    (key, value) = line.split(b":", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```
Catch the `ValueError` and raise a `MalformedProblemReport` exception instead (which is catched by `whoopsie-upload-all` and `apport-unpack`).
Bug: https://launchpad.net/bugs/1995100
=> fix: Catch ValueError: not enough values to unpack

apport/fileutils.py, tests/unit/test_fileutils.py
Desktop files shipped by Debian packages can be removed, which lets Apport crash:
```
File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
return func(*newargs, **newkeywargs)
File "tests/unit/test_fileutils.py", line 18, in test_find_package_desktopfile_deleted
apport.fileutils.find_package_desktopfile("blueman"), None
File "apport/fileutils.py", line 113, in find_package_desktopfile
with open(line, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/applications/non-existing/blueman.desktop'
```
Bug: https://launchpad.net/bugs/1997753
=> fix: Catch FileNotFoundError for missing desktop files

problem_report.py, tests/unit/test_problem_report.py
The problem report might be malformed which lets `whoopsie-upload-all` crash:
```
  File "data/whoopsie-upload-all", line 250, in <module>
    main()
  File "data/whoopsie-upload-all", line 232, in main
    stamps = collect_info()
  File "data/whoopsie-upload-all", line 163, in collect_info
    res = process_report(r)
  File "data/whoopsie-upload-all", line 77, in process_report
    r.load(f, binary="compressed")
  File "problem_report.py", line 147, in load
    bd, value = self._decompress_line(line, bd, value)
  File "problem_report.py", line 296, in _decompress_line
    block = base64.b64decode(line)
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```
Catch the …
=> fix: Catch binascii.Error: Incorrect padding

tests/integration/test_report.py
The `wait_for_proc_cmdline` helper method can success on the first try. Then the "sleep and retry" part of the function is not used which leads to a reduced code coverage.
Write test cases for the `wait_for_proc_cmdline` helper method to have full code coverage for it.
=> test: Test wait_for_proc_cmdline() helper method

apport/packaging_impl/apt_dpkg.py, tests/integration/test_packaging_apt_dpkg.py, tests/unit/test_packaging_apt_dpkg.py
`whoopsie-upload-all` might crash when there is no candidate in the APT cache for the Debian package:
```
  File "data/whoopsie-upload-all", line 250, in <module>
    main()
  File "data/whoopsie-upload-all", line 232, in main
    stamps = collect_info()
  File "data/whoopsie-upload-all", line 163, in collect_info
    res = process_report(r)
  File "data/whoopsie-upload-all", line 91, in process_report
    r.add_package_info()
  File "apport/report.py", line 371, in add_package_info
    version = self.add_package(package)
  File "apport/report.py", line 339, in add_package
    self._customized_package_suffix(package),
  File "apport/report.py", line 310, in _customized_package_suffix
    if not packaging.is_distro_package(package):
  File …
```
=> fix: Catch AttributeError: 'NoneType' object has no attribute 'origins'

data/bash-completion/apport-bug, data/bash-completion/apport-cli, data/bash-completion/apport-collect, data/bash-completion/apport-unpack, setup.py
The bash completions directory `/etc/bash_completion.d` is obsolete and the completions should be installed into
`/usr/share/bash-completion/completions`, which has stricter filename requirements.
Therefore move the bash completions into `data/bash-completion` and split each command into a separate file that matches the command name. Keep `apport-bug` and `apport-cli` in one file because they share the same helper functions.
Please review https://github.com/canonical/apport/pull/33 first to fix the missing code coverage for `setup.py`.
=> feat: Split bash completions by command

.github/workflows/ci.yaml, data/apport, data/systemd/apport.service, etc/init.d/apport, tests/unit/test_signal_crashes.py
Move start and stop logic from init.d service into `data/apport` to ease adding a corresponding systemd service. Do not move the pm-utils check for incomplete suspend/resume or hibernate, because pm-utils is not used any more in Ubuntu.
Add an apport systemd service as alternative to the init.d script.
=> feat: Add apport.service

data/apport, tests/unit/test_signal_crashes.py
Avoid calling `is_same_ns(host_pid, "mnt")` twice.
=> refactor(apport): Avoid duplicate is_same_ns() check

data/apport, tests/integration/test_signal_crashes.py
`str(signal.SIGXCPU)` returns `Signals.SIGXCPU` instead of the string representation of the signal number `24`. Therefore the comparison with the signal number string will never match.
=> fix: Fix ignoring SIGXCPU and SIGXFSZ

tests/unit/test_signal_crashes.py
Running the unit tests in autopkgtest leads to `init_error_log` changing `sys.stderr` and `sys.stdout` causing autopkgtest fail with exit status 120.
Mock `init_error_log` in the unit tests since these test should only tests the individual functions.
=> fix(tests): Mock init_error_log in unit tests

.github/workflows/ci.yaml, data/apport, tests/unit/test_signal_crashes.py
To make the code more readable, split `receive_arguments_via_socket` out of the `main` function.
Add some unit test cases for `receive_arguments_via_socket` to test failure cases (to increase test coverage).
=> refactor(apport): Split receive_arguments_via_socket out of main

problem_report.py, tests/unit/test_problem_report.py
apport-unpack will crash when passing a binary file that is not valid UTF-8:
```
$ apport-unpack /bin/ls unpack
File "/usr/lib/python3/dist-packages/problem_report.py", line 175, in load
(key, value) = line.split(b":", 1)
^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
During handling of the above exception, another exception occurred:
File "/usr/bin/apport-unpack", line 91, in <module>
main()
File "/usr/bin/apport-unpack", line 67, in main
pr = load_report(args.report)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/apport-unpack", line 47, in load_report
pr.load(f, binary=False)
File "/usr/lib/python3/dist-packages/problem_report.py", line 178, in load
f"Malformed problem report: Line …
```
=> fix: Catch UnicodeDecodeError on a malformed problem report

tests/integration/test_report.py, tests/integration/test_ui.py, tests/unit/test_rethread.py
Following changes in Python 3.11 causes some tests to fail:
* PEP 657 (Fine-grained error locations in tracebacks) changes the traceback strings.
* `re.py` was split into a directory with multiple files.
`apport/__init__.py` imports `impl` from `apport.packaging_impl` as `packaging`. So `apport.packaging` refers to
`apport.packaging_impl.impl`. Some change in Python 3.11 cause mocking the former fail. Therefore mock the real location of the object.
=> fix: Fix test failures with Python 3.11

tests/system/test_unkillable_shutdown.py
The `_wait_for_process` helper method can success on the first try. Then the "sleep and retry" part of the function is not used which leads to a reduced code coverage.
Write test cases for the `_wait_for_process` helper method to have full code coverage for it.
=> test: Test _wait_for_process() helper method

problem_report.py, tests/unit/test_problem_report.py
Unify error message for `MalformedProblemReport` to always state that the problem report is malformed and ask the user if this a proper .crash text file.
=> feat: Unify error message for MalformedProblemReport

tests/integration/test_java_crashes.py, tests/paths.py, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py
Add `local_path` parameter to `get_data_directory` to specify a subdirectory for the local source directory. This allows using `get_data_directory` without needing to differentiate between the local source directory and the installed data directory.
=> feat: Add local_path to get_data_directory()

apport/ui.py, tests/integration/test_ui.py
The attribute `UserInterface.args.tag` is singular, but it contains a list of tags. Rename `tag` to `tags` to reflect that to avoid confusion.
=> refactor: Rename args.tag to args.tags

apport/crashdb_impl/memory.py, doc/crashdb-conf.md, tests/integration/test_crash_digger.py, tests/integration/test_dupdb_admin.py, tests/integration/test_ui.py, tests/unit/test_crashdb.py
The word `dummy` in `dummy_data` may be insensitive. Therefore rename `dummy_data` to `sample_data`.
=> feat(crashdb/memory): Rename dummy_data to sample_data

apport/crashdb_impl/launchpad.py, apport/hookutils.py, apport/ui.py, data/apportcheckresume, data/general-hooks/generic.py, data/package_hook, doc/package-hooks.md, problem_report.py, tests/integration/test_hooks.py, tests/integration/test_hookutils.py, tests/integration/test_ui.py, tests/unit/test_problem_report.py
There are multiple Apport hooks that want to add tags to the report. Add `add_tags` and `get_tags` to `ProblemReport` to avoid code duplication.
=> refactor: Add add_tags() and get_tags() to ProblemReport

NEWS.md, data/unkillable_shutdown
The word `blacklist` may be insensitive. Use `omit_pids` instead.
=> feat(unkillable_shutdown): Rename blacklist to omit_pids

apport/ui.py, bin/apport-cli, gtk/apport-gtk, kde/apport-kde, tests/integration/test_ui.py, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py
Use a dataclass as response for `UserInterface.ui_present_report_details` instead of a dictionary. This ensures that the attributes are named correctly and allows specifying default values for the attributes.
=> refactor: Introduce apport.ui.Action dataclass

tests/paths.py
The path constants in `tests/path.py` are not used outside of the module.
=> refactor(test): Make path constants private

tests/integration/test_recoverable_problem.py
The `wait_for_report` helper method can success on the first try. Then the "sleep and retry" part of the function is not used which leads to a reduced code coverage.
Write test cases for the `wait_for_report` helper method to have full code coverage for it.
=> test: Test wait_for_report() helper method

data/apport, tests/unit/test_signal_crashes.py
To make the code more readable, split `sanity_checks` out of the `process_crash` function.
Add some unit tests for `sanity_checks` to increase the coverage of that function to 100% (when combined with the integration tests).
=> refactor(apport): Split sanity_checks out of process_crash

tests/integration/test_unkillable_shutdown.py, tests/system/test_unkillable_shutdown.py
The `_call` function only checks the stderr output if `expected_stderr` evaluates to `True`. This function is either called without setting `expected_stderr` or setting it to `""` (both evaluate to `False`).
Since all those test cases have log output on stderr, drop the checking code for the stderr output.
=> refactor: Drop unused check for stderr output in _call()

apport/__init__.py, kde/apport-kde
`gettext.gettext()` always returns Unicode strings in Python 3. Checking for type `bytes` was only needed for Python 2. The support for Python 2 has ended on beginning of 2020. So drop the Python 2 support from `unicode_gettext`.
`gettext.gettext()` needs to take a Unicode string as input. Otherwise it might return `bytes`.
=> feat: Drop Python 2 support from unicode_gettext

tests/unit/test_sandboxutils.py
Add some unit tests for `make_sandbox` from `apport.sandboxutils`.
=> test: Add unit tests for apport.sandboxutils

tests/integration/test_ui.py
The `REThread` calling `search_bug_patterns` can finish quickly so that `bpthread.is_alive()` in `collect_info` returns `False` on the call. Then the while loop not entered which leads to a reduced code coverage.
Enhance the test case `test_collect_info_package` to mock `search_bug_patterns` to sleep until the while loop is entered (to have code coverage for it).
=> fix: Cover bpthread.is_alive() while loop

tests/integration/test_report.py
The test case `test_check_interpreted` triggers a deprecation warning: "The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives"
`Report._python_module_path` uses `importlib.util.find_spec` which tries to find the spec for the module (but does not execute the module).
Replace `distutils.cmd` by `http.server` in the test, which is a real world example:
```
python3 -m http.server 8080
```
=> fix: Replace deprecated distutils for report test

apport/report.py, data/apport, etc/apport/report-ignore/README.denylist, tests/integration/test_report.py
The words `blacklist` and `whitelist` may be insensitive. Therefore rename the directory `/etc/apport/blacklist.d` to `/etc/apport/report-ignore` and `/etc/apport/whitelist.d` to `/etc/apport/report-only`. Keep reading the old directories for backward compatibility until Apport 3.0.
This merge request contains the commit from #92: Avoid code duplication in `Report.check_ignored` by factoring out the list files reading into `_read_list_files_in_directory`.
=> feat: Replace blacklist.d/whitelist.d by report-ignore/report-only directories

tests/unit/test_crashdb.py
Add a test case for `check_duplicate()` with multiple regressions to trigger the code path `packaging.compare_versions` in `CrashDatabase._duplicate_search_signature`.
=> test: Test check_duplicate() with multiple regressions

apport/ui.py, bin/apport-cli, gtk/apport-gtk, kde/apport-kde, tests/integration/test_ui.py
The word `blacklist` may be insensitive. Rename the `Action` property `blacklist` to  `ignore`.
=> refactor: Rename Action.blacklist to Action.ignore

apport/crashdb.py
`apport.crashdb` imports `apport.report`, but only uses `apport.packaging` (which is declared in `apport/__init__.py`).
Import `packaging` directly from `apport.packaging_impl` instead. This change is needed to avoid circular imports when fixing https://launchpad.net/bugs/2003098.
=> fix: Import needed packaging library directly

tests/integration/test_hooks.py, tests/integration/test_signal_crashes.py, tests/system/test_packaging_apt_dpkg.py
Replace `TestCase.fail` with `TestCase.assert*` calls that are always executed to increase the code coverage.
The statements after `self.fail` in
`test_install_packages_permanent_sandbox` were indented incorrectly, because the code after `self.fail` is unreachable.
=> refactor: Replace TestCase.fail by TestCase.assert*

.github/workflows/ci.yaml, .pylintrc, NEWS.md
Run `woke` on the source code in the CI to avoid regressions.
=> ci: Run woke on the source code

data/apport, tests/unit/test_signal_crashes.py
Checking for root processes does not belong into `is_closing_session`.
Add unit tests for `is_closing_session()` to increase code coverage to ease future refactoring.
=> test: Add unit tests for is_closing_session()

kde/apport-kde
`apport-kde` imports `apport` but only uses `apport.logging` from it.
Import `apport.logging` directly instead. This change is needed to avoid circular imports when fixing https://launchpad.net/bugs/2003098.
=> refactor(kde): Import apport.logging library directly

.github/workflows/ci.yaml, tests/integration/test_hooks.py, tests/integration/test_hookutils.py, tests/integration/test_packaging_apt_dpkg.py, tests/integration/test_report.py, tests/integration/test_ui.py, tests/system/test_packaging_apt_dpkg.py, tests/system/test_python_crashes.py, tests/system/test_ui_gtk.py, tests/unit/test_signal_crashes.py
The Python crashes system tests need `dbus`, the GTK UI system tests need GI and the Glib/GTK libraries, and `test_receive_arguments_via_socket_invalid_socket` needs the systemd library. Check for the presence and skip if the libraries are missing.
Some test cases need some binaries for their test which might not be installed. Check for the presence and skip if the binaries are missing.
Run all tests in a minimal container to check if they are skipped or succeed.
=> test: Skip tests if Python dependencies or required binaries are missing

data/apport
Return boolean directly in `is_closing_session()` instead of wrapping it in an useless if-statement.
=> refactoring(apport): Return boolean directly in is_closing_session()

apport/__init__.py, apport/ui.py, bin/apport-cli, bin/apport-retrace, bin/apport-unpack, bin/apport-valgrind, data/apportcheckresume, data/kernel_oops, gtk/apport-gtk, kde/apport-kde, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py, tests/unit/test_deprecation.py
Use `gettext.gettext()` directly and deprecate `apport.unicode_gettext()`. Use `PendingDeprecationWarning` for now, because it is not shown by default. Please change that to `DeprecationWarning` once no package in the Ubuntu archive uses `unicode_gettext` any more.
=> feat: Deprecate apport.unicode_gettext()

tests/integration/test_python_crashes.py
pytest-cov 4.0 does not print a stack trace in the `test_deleted_working_directory` test case any more, but only prints an one-liner:
```
pytest-cov: Failed to setup subprocess coverage. Environ: [...] Exception: FileNotFoundError(2, 'No such file or directory')
```
So extend `test_deleted_working_directory` to also only strip this one pytest-cov line from the stderr output.
=> test: Fix test_deleted_working_directory for pytest-cov 4.0

apport/report.py, apport/ui.py, data/whoopsie-upload-all, tests/integration/test_report.py
Commit f8edc7280d492e710218c193e53542f1f86cfa91 introduces a regression: The package specific hooks are not run in `whoopsie-upload-all` because `add_hooks_info` is called with `ui=None`. `add_hooks_info` will raise an `AssertionError` for `ui=None`.
Use `NoninteractiveHookUI()` when `ui` is set to `None`.
Bug: https://launchpad.net/bugs/2003098
=> fix(whoopsie-upload-all): Use NoninteractiveHookUI for add_hooks_info

apport/fileutils.py, apport/report.py, data/apport, tests/unit/test_fileutils.py
Reduce duplicate code by introducing `apport.fileutils.get_process_environ` which reads and parses the process environ. Also make `Report.add_proc_environ` more readable by move some logic into a new `_Environment` object.
=> refactor: Introduce get_process_environ

tests/integration/test_java_crashes.py
The Java crashes tests check that the `java` command is available and `setUp` checks that `apport.jar` is present. In that case `crash.class` and `crash.jar` should also have been built by `setup.py`. So convert these checks into assertions to increase code coverage.
=> tests: Expect crash .class and .jar to be present

apport/crashdb.py
`cmp()` in `CrashDatabase._duplicate_search_signature()` has more if-conditions than return values. Group them by return value:
| x    | y    | return |
|------|------|--------|
| None | None | 0      |
| ""   | ""   | 0      |
| None | ""   | 1      |
| None | .*   | 1      |
| ""   | .*   | 1      |
| ""   | None | -1     |
| .*   | None | -1     |
| .*   | ""   | -1     |
=> refactor: Simplify cmp() in CrashDatabase._duplicate_search_signature

tests/unit/test_signal_crashes.py
Test `init_error_log()` doing nothing on a TTY.
=> test: Add test_init_error_log_is_tty()

data/apport
Return early in `init_error_log` to reduce the indentation level and make the function more readable.
=> refactor(apport): Return early in init_error_log

data/apport
To make the code better readable, use the standard `logging` library for logging in `data/apport`.
=> refactor(apport): Use logging library for logging

tests/integration/test_packaging_apt_dpkg.py
Mark error case in `test_get_file_package_diversion` with no cover since this code path is only triggered in the test failure case.
=> test: Mark error case in test_get_file_package_diversion with no cover

data/apport
Let argparse check that the arguments are of type int for `--pid`, `--signal-number`, `--core-ulimit`, `----dump-mode`, and `--global-pid`.
=> refactor(apport): Let argparse check type of arguments

tests/integration/test_signal_crashes.py
To use the apport path for imports in future commits, make `apport_path` a public variable.
=> refactor(test): Make apport_path a public variable

data/apport
The socket in `forward_crash_to_container` is not closed.
=> fix: Close socket in forward_crash_to_container

data/apport
The use of f-strings is preferred instead of using the `%` formatting operator.
=> refactor(apport): Use f-strings

apport/crashdb.py, apport/crashdb_impl/debian.py, apport/crashdb_impl/launchpad.py, apport/crashdb_impl/memory.py, apport/ui.py, tests/integration/test_ui.py
Some crashdb backends might need to display messages to the user, here's a safe API to do so.
See individual commit logs for more detailed descriptions of the changes.
This is an offshoot of #26
=> ui: upload-time messaging

.github/workflows/ci.yaml
The two tests in `tests/system/test_signal_crashes.py` are skipped if there are `.crash` files in /var/crash.
=> ci: Cleanup /var/crash/ for system-tests-installed

tests/system/test_unkillable_shutdown.py
If the unkillable shutdown test cases fail, the `_run_test_executable` runner might continue running. Ensure that the runner and the test process is killed in all cases.
=> tests: Ensure runner is killed in failure case

tests/run-linters
Black and pylint might complain about Python files in `.pc` that were created by quilt containing pre-patch versions of the Python files. Pylint might also check files in `.pybuild`. All these files should not be checked by the linters.
=> test: Specify Python files for linters directly

.github/workflows/ci.yaml, apport/crashdb_impl/github.py, apport/report.py, apport/ui.py, doc/crashdb-conf.md, etc/apport/crashdb.conf, tests/integration/test_github.py, tests/unit/test_report.py
This builds on Edu's work on https://github.com/canonical/apport/pull/1, to add this functionality: If a snap contact: field points to Github, report it there.
The snap report can be tested by installing [this snap](https://github.com/canonical/snap-for-apport-reports/) and then running `apport-bug apport-target`.
=> Add GitHub backend for WSL and snaps

apport/report.py, data/apport, data/whoopsie-upload-all
The package info is added to the crash report when the report is reported by the user or when it is uploaded. There can be quite some time delay and the list of installed packages could have change since then. There are crashes on errors.ubuntu.com where the reported version is newer than the code in the Python stack trace. So this kind of discrepancy happens in the real world.
So try to add the package info during crash. Add a `HooksRun` entry to the report to document that the hooks were not run (for `whoopsie-upload-all`). Change `add_package_info` to not overwrite existing entries.
=> feat: Already add package info during crash

.github/workflows/ci.yaml, data/whoopsie-upload-all, tests/integration/test_github.py, tests/run-linters
Run black with `--skip-magic-trailing-comma` to not use trailing commas as a reason to split lines. This will fold lines that became short enough.
=> style: Format Python code with black -C

apport/report.py, tests/integration/test_report.py
The fields `Snap.Changes`, `Snap.Connections`, `Snap.Info.*` contain binary instead of a string. Let `_command_output` return `str` instead of `bytes`.
=> fix: Let _command_output return str instead of bytes

apport/report.py
Remove dots from report keys `Snap.Changes`, `Snap.Connections`, and `Snap.Info` for consistency.
=> feat: Remove dots from Snap.* report keys (for consistency)

apport/report.py, tests/integration/test_report.py
Strip trailing whitespaces from Snap* values.
=> fix: Strip trailing whitespaces from Snap* values

tests/integration/test_signal_crashes.py
Running `test_core_dump_packaged_sigquit_via_socket` in a container runs into a timeout:
```
test_core_dump_packaged_sigquit_via_socket (tests.integration.test_signal_crashes.T.test_core_dump_packaged_sigquit_via_socket)
Executable create core files via socket, no report for SIGQUIT. ... 46	../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
warning: target file /proc/4067/cmdline contained unexpected null characters
ERROR:root:user is trying to trick apport into accessing a socket that doesn't belong to the container
autopkgtest [05:27:10]: kill with SIGTERM did not work sending SIGKILL
```
Mock the `apport.fileutils.search_map` calls to prevent not forwarding the test crash to the container.
=> fix: Support running signal crash via socket tests in containers

apport/ui.py, tests/integration/test_ui.py
Uploading the crash report can fail with a `HTTPError`:
```
File "/usr/share/apport/apport-gtk", line 698, in <module>
app.run_argv()
File "/usr/lib/python3/dist-packages/apport/ui.py", line 933, in run_argv
return self.run_crashes()
^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/apport/ui.py", line 333, in run_crashes
self.run_crash(f)
File "/usr/lib/python3/dist-packages/apport/ui.py", line 438, in run_crash
self.file_report()
File "/usr/lib/python3/dist-packages/apport/ui.py", line 1852, in file_report
upthread.exc_raise()
File "/usr/lib/python3/dist-packages/apport/REThread.py", line 62, in exc_raise
raise self._exception[1].with_traceback(self._exception[2])
File "/usr/lib/python3/dist-packages/apport/REThread.py", line 37, in run …
```
=> fix: Catch HTTPError in UserInterface.file_report

data/apport, tests/unit/test_signal_crashes.py
Following unhandled exception of apport was found on a bug report:
```
ERROR: apport (pid 21210) Fri Feb 24 16:07:46 2023: Unhandled exception:
File "/usr/share/apport/apport", line 848, in main
get_pid_info(pid)
File "/usr/share/apport/apport", line 98, in get_pid_info
proc_pid_fd = os.open(
^^^^^^^^
```
Print a proper error message and exit in this case.
Bug: https://launchpad.net/bugs/2008638
=> fix(apport): Print proper error message if /proc/<pid> is gone

apport/crashdb_impl/launchpad.py, apport/packaging_impl/rpm.py, apport/ui.py, gtk/apport-gtk
pylint 2.16.2 complains:
```
************* Module apport.ui
apport/ui.py:1567:20: W0101: Unreachable code (unreachable)
************* Module apport.packaging_impl.rpm
apport/packaging_impl/rpm.py:184:12: W0719: Raising too general exception: Exception (broad-exception-raised)
************* Module apport.crashdb_impl.launchpad
apport/crashdb_impl/launchpad.py:397:16: W0719: Raising too general exception: Exception (broad-exception-raised)
************* Module gtk.apport-gtk
gtk/apport-gtk:678:8: W0101: Unreachable code (unreachable)
```
Remove the unreachable code and replace both exceptions with `NotImplementedError` which is more precise.
=> chore: Fix pylint 2.16.2 complains

etc/apport/crashdb.conf
`bug_pattern_url` must be a URL and not only a file. Otherwise apport will fail:
```
File "/usr/share/apport/apport-gtk", line 698, in <module>
app.run_argv()
File "/usr/lib/python3/dist-packages/apport/ui.py", line 868, in run_argv
return self.run_report_bug()
File "/usr/lib/python3/dist-packages/apport/ui.py", line 627, in run_report_bug
self.collect_info(symptom_script)
File "/usr/lib/python3/dist-packages/apport/ui.py", line 1624, in collect_info
bpthread.exc_raise()
File "/usr/lib/python3/dist-packages/apport/REThread.py", line 62, in exc_raise
raise self._exception[1].with_traceback(self._exception[2])
File "/usr/lib/python3/dist-packages/apport/REThread.py", line 37, in run
self._retval = self.__target(*self.__args, **self.__kwargs)
File …
```
=> fix: Use URL for debug bug pattern URL

apport/report.py, bin/apport-retrace
Running `lay src` in the GDB session opened by `apport-retrace` fails with:
```
(gdb) lay src
Cannot enable the TUI: error opening terminal [TERM=<unset>]
```
This is caused by calling `gdb` with a minimal environment that does not include `TERM`.
Keep the minimal environment for `Report.add_gdb_info` (for not translating the gdb output), but use the full environment when an interactive GDB session is started via `apport-retrace`.
Bug: https://launchpad.net/bugs/2012374
=> apport-retrace: Do not drop environment variables when calling GDB

apport/hookutils.py, tests/unit/test_hookutils.py
When using journalctl to extract the "recent" syslog messages, the `--system` option was unconditionally passed. This means messages from the user journal are not included. Added a parameter of `recent_syslog` to /not/ pass the `--system` option to journalctl ; so that everything the current user sees (including output of commands run with `systemd-run --user`) is included if requested.
To use the new option, the caller must invoke `recent_syslog` with the `journald_system_only=False` keyword argument. By default, its value is set to True so that the default behavior remains unchanged.
This is something we'd need for subiquity since we rely on `systemd-run --user` quite often.
=> feat: allow recent_syslog to collect all journal messages that the user can see

apport/ui.py, apport/user_group.py, tests/integration/test_ui.py, tests/unit/test_user_group.py
By setting the environment variable `SUDO_UID` or `PKEXEC_UID` Apport can be tricked into calling `xdg-open` via sudo for the specified user ID.
Prevent that unexpected behavior if Apport was not called as root.
=> fix: Only open browser as user (via sudo) if running as root

.github/workflows/ci.yaml
Uploading the coverage report to Codecov often fails with:
['error'] There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
=> ci: Use secret token for Codecov upload

data/general-hooks/wayland_session.py, tests/unit/test_hooks_wayland_session.py
Add general hook `wayland_session.py` that adds a `wayland-session` tag if the current session is running under Wayland. This general hook has been taken from the Ubuntu package.
Bug: https://launchpad.net/bugs/1418262
=> feat: Add general hook wayland_session.py

po/ca.po, po/th.po
Import translation updates from
https://translations.launchpad.net/ubuntu/lunar/+source/apport for languages that have updates. Do not update translations that have no changes except for updated metadata (POT-Creation-Date, X-Launchpad-Export-Date, and X-Generator). Do not import Moroccan Tamazight translation (`zgh.po`) since it does not contain translations yet.
=> feat: Import translation updates from Ubuntu 23.04 (lunar)

bin/apport-unpack, tests/integration/test_apport_unpack.py
Commit b06d44fb61e51dd637cab89452b7c6b632c7e243 catches `binascii.Error` and raise a `MalformedProblemReport` exception instead, but `apport-unpack` does not catch `MalformedProblemReport` on extracting the keys:
```
$ printf "CoreDump: base64\n H4sICAAAAAAC/0NvcmVEdW1wAA==\n 7Z0LYFPV/cdP0rQ\n" > malformed.crash
$ apport-unpack malformed.crash unpack
File "/usr/bin/apport-unpack", line 91, in <module>
main()
File "/usr/bin/apport-unpack", line 85, in main
pr.extract_keys(f, bin_keys, args.target_directory)
File "/usr/lib/python3/dist-packages/problem_report.py", line 254, in extract_keys
bd, line_value = self._decompress_line(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/problem_report.py", line 316, in _decompress_line
raise …
```
=> fix(apport-unpack): Catch MalformedProblemReport on extraction

apport/packaging.py
```
apport/packaging.py:59: error: All conditional function variants must have identical signatures
```
Add type hints to `freedesktop_os_release`.
=> refactor: Add type hints to freedesktop_os_release

.pylintrc, apport/crashdb.py, apport/crashdb_impl/launchpad.py, apport/hookutils.py, apport/packaging_impl/apt_dpkg.py, apport/report.py, apport/sandboxutils.py, apport/ui.py, apport_python_hook.py, bin/apport-retrace, data/apport, data/general-hooks/generic.py, data/general-hooks/parse_segv.py, data/whoopsie-upload-all, gtk/apport-gtk, kde/apport-kde, problem_report.py, tests/integration/test_fileutils.py, tests/integration/test_hookutils.py, tests/integration/test_problem_report.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/system/test_packaging_apt_dpkg.py, tests/unit/test_crashdb.py, tests/unit/test_parse_segv.py, tests/unit/test_report.py
To prevent introducing big functions, add `TODO`s for functions/methods that should be split and remove the override from the global pylint configuration.
=> chore: Add todos for functions/methods that should be split

tests/integration/test_ui.py
The test `test_run_as_real_user_no_sudo` can fail if the environment has `SUDO_UID` set and is run as root:
```
FAIL: test_run_as_real_user_no_sudo (tests.integration.test_ui.T.test_run_as_real_user_no_sudo)
Test run_as_real_user() without sudo env variables.
File "/usr/lib/python3.11/unittest/mock.py", line 1369, in patched
return func(*newargs, **newkeywargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/unittest/mock.py", line 1822, in _inner
return f(*args, **kw)
^^^^^^^^^^^^^^
File "/tmp/autopkgtest.Z6SSWK/autopkgtest_tmp/tests/integration/test_ui.py", line 2779, in test_run_as_real_user_no_sudo …
```
=> fix(tests): Clear environment for test_run_as_real_user_no_sudo

data/apport
Logging the output of the `gdbus` belongs to the debug level and should not be printed with warning level.
=> fix(apport): Demote debug gdbus log to debug level

apport_python_hook.py
Commit ea64857890ac6cb8ad056af255cf7b706850bea7 ("feat: Already add package info during crash") added the package info to the crash report during crash to prevent package list discrepancies between crash and reporting. This commit only changed reports for crashes of compiled programs.
Apply the same logic to Python crashes. Apport uses `apport_python_hook` for Python to intercept stack traces.
=> feat: Already add package info during Python crashes

.pylintrc, apport/crashdb.py, apport/crashdb_impl/github.py, apport/crashdb_impl/launchpad.py, apport/crashdb_impl/memory.py, apport/packaging.py, apport/packaging_impl/apt_dpkg.py, apport/sandboxutils.py, bin/crash-digger, tests/integration/test_signal_crashes.py
Increase the allowed maximum arguments to six and move the overrides to the individual functions/methods.
=> refactor: Increase pylint's max args to 6

data/apport
The global variable `cwd` is only used in `write_user_coredump`. So defining it can be deferred until `write_user_coredump` is called and `cwd` can be private to `write_user_coredump`.
=> refactor(apport): Make cwd a private variable

.pylintrc, apport/crashdb_impl/launchpad.py, apport/hookutils.py, apport/packaging_impl/apt_dpkg.py, apport/report.py, apport/ui.py, data/apport, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/system/test_packaging_apt_dpkg.py, tests/system/test_ui_gtk.py, tests/unit/test_report.py
Move pylint's too-many-lines overrides to affected files to allow getting this alert for new cases.
=> refactor: Move pylint's too-many-lines overrides to affected files

data/apport
Apport only used error log message even for purely informational logs. Since `logging` is used nowadays, demote the non-error log messages to info level. Reduce the log level from warning to info to still print these messages.
=> fix(apport): Demote non-error log messages to info level

apport/fileutils.py, apport/report.py, doc/data-format.tex, tests/integration/test_signal_crashes.py, tests/unit/test_fileutils.py
The test case `test_crash_apport` will fail if the test executing user is member of a system group with an ID between 500 and 999:
```
FAIL: test_crash_apport (tests.integration.test_signal_crashes.T.test_crash_apport)
Report generation with apport.
File "/<<PKGBUILDDIR>>/tests/integration/test_signal_crashes.py", line 211, in test_crash_apport
self.assertLess(grp.getgrnam(g).gr_gid, 500)
AssertionError: 992 not less than 500
```
The default maximum system user/group ID on Debian based systems in 999 (defined in `/etc/login.defs`), but the Linux …
=> fix: Correct range of system users/groups from 499 to dynamic 999

tests/integration/test_ui.py
The value `pw_gecos` contains a comma separated list where the first element might be the full user name. Split the first element from `pw_gecos` (if it is not empty) to check that the full name is not in the crash report.
=> fix(tests): Fix check for full name in test_run_crash_anonymity

tests/integration/test_ui.py
```
tests/integration/test_ui.py:523: error: Incompatible default for argument "bash_hook" (default has type "None", argument has type "str")  [assignment]
tests/integration/test_ui.py:523: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
tests/integration/test_ui.py:523: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
```
=> fix(tests): Fix type hint for _write_crashdb_config_hook

.pylintrc, apport/crashdb.py, apport/crashdb_impl/launchpad.py, apport/packaging_impl/apt_dpkg.py, apport/ui.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/system/test_ui_gtk.py, tests/unit/test_crashdb.py, tests/unit/test_problem_report.py
Increase the allowed maximum public methods to 25 and move the overrides to the individual classes. It is okay for test case classes to have more than 25 tests inside.
=> refactor: Increase pylint's maximum public methods to 25

apport/ui.py, bin/apport-cli, tests/integration/test_ui_cli.py
Move saving the problem report in a temporary directory into a separate function. Assert that `self.report` is not `None` to make mypy happy.
=> refactor(apport-cli): Move saving the report into a separate function

gtk/apport-gtk, kde/apport-kde
```
gtk/apport-gtk:238: error: "None" has no attribute "get"  [attr-defined]
gtk/apport-gtk:280: error: Value of type "None" is not indexable  [index]
gtk/apport-gtk:413: error: Unsupported right operand type for in ("None")  [operator]
gtk/apport-gtk:414: error: Value of type "None" is not indexable  [index]
kde/apport-kde:130: error: "QObject" has no attribute "setRange"  [attr-defined]
kde/apport-kde:131: error: "QObject" has no attribute "setValue"  [attr-defined]
kde/apport-kde:133: error: "QObject" has no attribute "setRange"  [attr-defined]
kde/apport-kde:134: error: "QObject" has no attribute "setValue"  [attr-defined]
kde/apport-kde:413: error: Incompatible types in assignment (expression has type "ReportDialog", variable has type "None")  [assignment] …
```
=> refactor(gtk/kde): Add assertions to make mypy happy

data/apport, tests/integration/test_signal_crashes.py
Instead of using `proc_pid_fd` in `is_same_ns()` just specify the path to the cgroup file. The other code in the function does that already.
=> refactor(apport): Drop using proc_pid_fd from is_same_ns

apport/report.py, tests/integration/test_report.py
```
apport/report.py:179: error: On Python 3 formatting "b'abc'" with "{}" produces "b'abc'", not "abc"; use "{!r}" if this is desired behavior  [str-bytes-safe]
apport/report.py:180: error: Item "None" of "Optional[bytes]" has no attribute "rstrip"  [union-attr]
```
The mypy complains can be converted into a test case that fail:
```
ERROR: test_command_output_timeout_no_output (tests.integration.test_report.T.test_command_output_timeout_no_output)
File "/home/bdrung/projects/apport/apport/apport/report.py", line 169, in _command_output
sp = subprocess.run(
^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/subprocess.py", line 550, in run
stdout, stderr = …
```
=> fix: Fix raising OSError if _command_output() runs into a timeout

data/general-hooks/generic.py, tests/integration/test_hooks.py
Running the generic general hook manually fails:
```
$ python3 data/general-hooks/generic.py
File "/home/bdrung/projects/apport/apport/data/general-hooks/generic.py", line 129, in <module>
add_info(r, None)
File "/home/bdrung/projects/apport/apport/data/general-hooks/generic.py", line 123, in add_info
if report["ProblemType"] == "Crash":
~~~~~~^^^^^^^^^^^^^^^
KeyError: 'ProblemType'
```
Use an instance of `ProblemReport` like Apport would use.
=> fix: Use ProblemReport for running generic hook manually

tests/integration/test_ui.py
The test `test_run_crash_anonymity` can fail if the user or host name is short:
```
FAIL: test_run_crash_anonymity (tests.integration.test_ui.T)
run_crash() anonymization
File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
return func(*newargs, **newkeywargs)
File "/<<PKGBUILDDIR>>/tests/integration/test_ui.py", line 1650, in test_run_crash_anonymity
self.assertNotIn(
AssertionError: 'kin' unexpectedly found in 'ProblemType: Crash\nArchitecture: amd64\n[...]'
```
The string `kin` can be found in the report (for example in the tag `kinetic`). So only search for full words in the report if the string …
=> fix(tests): Fix false positives for test_run_crash_anonymity

data/apport
Replace `os.path.exists` check by trying to open the file and catching `FileNotFoundError` to avoid race conditions.
=> fix(apport): Replace os.path.exists check by try-except

.github/workflows/ci.yaml, apport/ui.py, setup.py, tests/integration/test_apport_unpack.py, tests/integration/test_ui.py, tests/run-linters
Add type hints for mypy and run mypy on the Python modules as part of `tests/run-linters`. Install mypy and python3-typeshed for the linter CI test.
=> tests: Run mypy on Python modules

kde/apport-kde
```
kde/apport-kde:74: error: Incompatible types in assignment (expression has type "Callable[[Any, Any], Any]", variable has type "Callable[[Properties, Any, Any], Any]")  [assignment]
```
`PyQt5.uic.properties.Properties._string` has the additional parameter `notr` since at least PyQt 5.10.1 (tested on Ubuntu 18.04 "bionic"). The `_string` method has not been changed since then (tested PyQt5 5.15.9 on Ubuntu 23.04 "lunar").
Add `notr` parameter to the `translate` function and make the code more similar to the upstream code.
=> fix(apport-kde): Add notr parameter to translate function

data/apport, tests/unit/test_signal_crashes.py
Replace global variable `proc_pid_fd` by an `ProcPid` instance that is a context manager to ensure the opened file will be closed.
=> refactor(apport): Replace global proc_pid_fd by ProcPid

NEWS.md, apport/crashdb_impl/launchpad.py, apport/hookutils.py, apport/report.py, apport/sandboxutils.py, apport/ui.py, apport_python_hook.py, data/general-hooks/generic.py, doc/crashdb-conf.md, doc/data-format.tex, man/dupdb-admin.1, problem_report.py, pyproject.toml, tests/integration/test_problem_report.py, tests/integration/test_report.py, tests/integration/test_ui.py, tests/system/test_packaging_apt_dpkg.py, tests/unit/test_crashdb.py, tests/unit/test_parse_segv.py, tests/unit/test_problem_report.py, tests/unit/test_report.py
`codespell .` finds several spelling mistakes. Address all of them (except for two false positives that can be addressed later).
=> fix: Fix spelling mistakes found by codespell

data/apport, tests/unit/test_signal_crashes.py
Group user and group ID in a `UserGroupID` data class and hand around that data class instead of using a global variable.
=> refactor(apport): Use UserGroupID data class

.github/workflows/ci.yaml, tests/README.md, tests/system/test_packaging_apt_dpkg.py
Using idiomatic pytest is more concise than Python's builtin unittest framework, and will allow us to use some of pytest goodies, such as test parametrization, which is used to great effect in #193 
I also updated the testing README to remove any mention of `unittest`, as I expect this PR will shine the way to a new, unittest-free world ;)
=> Migrate the APT tests to pytest

.github/workflows/ci.yaml, README.md, apport/packaging.py, apport/packaging_impl/__init__.py, apport/packaging_impl/apt_dpkg.py, tests/unit/test_packaging_impl.py
The latest Debian stable is Bookworm, not Bullseye anymore.
=> Bump the lowest Debian version to Bookworm in CI

data/apport, kde/apport-kde, tests/run-linters
mypy claims that `sys.stdin` has the type `io.TextIO` to ease redefining it. So assert that `sys.stdin` is still `io.TextIOWrapper` to make mypy happy.
Run mypy on the Python scripts. This needs to be done separately for each script because there is only one entry point allowed by mypy.
=> tests: Also run mypy on all Python scripts

data/gcc_ice_hook
This line bugs out once in a while in pylint ever since we enabled parallelism. Since the parallel gains are substantial, let's just disable the check there.
=> gcc_ice_hook: Disable buggy pylint check

apport/packaging_impl/apt_dpkg.py, tests/integration/test_packaging_apt_dpkg.py, tests/system/test_packaging_apt_dpkg.py
This PR contains various refactoring that will make it much easier to implement support for the APT deb822 source format.
=> Deb822 prologue: refactorings

apport/packaging_impl/apt_dpkg.py, tests/system/test_packaging_apt_dpkg.py, tests/unit/test_packaging_apt_dpkg.py
There's a (somewhat) new format for sources definition supported by APT, based on the deb822 syntax that's widely used in the Debian world. The APT developpers would like to make that new format the default (there are plenty of good reasons), and for that we need to support it.
Luckily some of the heavy lifting has already been done in `python-apt`.
Note that in order to easily test the new format, I migrated `tests/system/test_packaging_apt_dpkg.py` from using the unittest API to directly use pytest's API, since we're already using it as test runner anyway (split off in #194). This allowed me to simply parameterize the tests over the source format, ensuring a good test coverage. Said migration should account for a good chunk of the test file diff.
=> Implement APT deb822 support (FR-4091)

apport/crashdb_impl/github.py, apport/fileutils.py, apport/hookutils.py, apport/report.py, apport/ui.py, bin/apport-cli, data/apport, gtk/apport-gtk, kde/apport-kde, problem_report.py, tests/helper.py, tests/integration/test_apport_checkreports.py, tests/integration/test_dupdb_admin.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/integration/test_unkillable_shutdown.py, tests/paths.py, tests/run-linters, tests/system/test_packaging_apt_dpkg.py
Some functions/methods were only partially anotated with types. Complete those annotations. Use `typing.Any` for too complicated cases. This could be refined in the future.
Fix two issues found:
* `Report.add_hooks_info` could return `None` despite the docstring that this methods return a boolean. So return `False` in the `None` case.
* apport: Assert that coredump_fd is set before using it
When annotating function they should be annotated completely (for consistency). So use `--disallow-incomplete-defs` from the set of strict rules.
=> test: Run mypy with --disallow-incomplete-defs

bin/crash-digger, tests/integration/test_crash_digger.py
Brian was working on moving the service which retraces apport crashes in Launchpad to a different server and noticed that while the existing service uses crash-digger it does not take advantage of the GDB sandbox option which he added to apport some time ago. He has added an option to crash-digger, --gdb-sandbox, which is then is then passed through as argument to apport-retrace.
Also add a test case for crash-digger --gdb-sandbox.
=> crash-digger: Add support for using a gdb-sandbox (plus test case)

bin/apport-cli
intltool fails to extract the gettext call inside a f-string (see https://savannah.gnu.org/bugs/?61596). So move the gettext call out of
the f-string.
Fixes: 5a504336b2f6bafd82f268c5dc5e9a4db4cc9bcd ("refactor: Use f-strings everywhere")
=> apport-cli: Move gettext call out of f-string

apport/ui.py
The formatting string needs to be passed gettext before replacing the dynamic parts. This has been broken for several years.
Fixes: 300552f44369ff06647f30ab79072af6ebfc5ac9 ("merge recent changes from trunk")
=> ui: Fix translating the web browser opening error message

tests/integration/test_ui.py
Our context manager improperly failed to deal with exceptions thrown in the block under context, resulting in the test process never being killed.
See https://github.com/pytest-dev/pytest/issues/3365
=> tests: ui: fix hangup on test failure

apport/packaging_impl/apt_dpkg.py, tests/system/test_packaging_apt_dpkg.py
When instantiating `apt.Cache` with `rootdir` set to something else than `None`, it tries to create the required directories. When running not as root and `/etc/apt/sources.list` not being present, it will fail with `PermissionError` (see https://launchpad.net/bugs/1974015).
So leave `rootdir` unset to let the cache use the system sources.list and system lists/files without trying to create `/etc/apt/sources.list`.
=> apt_dpkg: Drop rootdir="/" from apt.Cache

tests/integration/test_packaging_apt_dpkg.py
Ubuntu used to have a dpkg diversion for dash, but that changed in Ubuntu 23.10 (mantic). Skip the integration test
`test_get_file_package_diversion` if the system has no diversion.
Bug: https://launchpad.net/bugs/2028879
=> Skip test_get_file_package_diversion if the system has no diversion

tests/integration/test_recoverable_problem.py, tests/integration/test_signal_crashes.py
pylint 2.17.4 complains:
```
************* Module tests.integration.test_recoverable_problem
tests/integration/test_recoverable_problem.py:34:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
************* Module tests.integration.test_signal_crashes
tests/integration/test_signal_crashes.py:1175:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
```
Silence those false positives.
=> test: Silence false inconsistent-return-statements

.github/workflows/cla.yaml
Apport requires to have the Canonical Contributor Licence Agreement (CLA) to be signed.
=> ci: Add check for Contributor Licence Agreement (CLA)

apport/report.py, tests/unit/test_report.py
The previous version would actually simply return invalid values instead
of raising, and the code that would raise would first *use* said values,
leading to crashes, despair, and bug reports.
In addition, this PR contains some more type hints (that would have caught this!!) and a small drive-by cosmetic fix.
=> fix: raise "gdb not found" as soon as detected (LP: #2031919)

.github/workflows/ci.yaml, apport/packaging_impl/apt_dpkg.py, tests/unit/test_packaging_apt_dpkg.py
The test case `TestApportValgrind.test_sandbox_cache_options` started to fail on the system-tests-installed CI run:
```
dpkg-deb: error: '/tmp/tmp4wlfuaxh/test-cache/system/apt/var/lib/apt/lists/auxfiles/_etc_apt_apt-mirrors.txt' is not a Debian format archive
File "/usr/bin/apport-valgrind", line 159, in <module>
sandbox, cache, outdated_msg = apport.sandboxutils.make_sandbox(
File "/usr/lib/python3/dist-packages/apport/sandboxutils.py", line 226, in make_sandbox
outdated_msg = packaging.install_packages(
File "/usr/lib/python3/dist-packages/apport/packaging_impl/apt_dpkg.py", line 1302, in install_packages
out = subprocess.check_output(["dpkg-deb", "--show", i.destfile]).decode()
File "/usr/lib/python3.10/subprocess.py", line 421, in check_output …
```
=> apt_dpkg: Add basic support for mirror+file: URIs

apport/fileutils.py
As discussed in #216 , [typing.Dict](https://docs.python.org/3/library/typing.html#typing.Dict) is deprecated.
=> fix: deprecated typing.Dict

apport/ui.py, tests/integration/test_ui.py
Ever since we've started collecting deps info at crash file creation, that code path was essentially dead, and that resulted in the _MarkForUpload field never touched in some circumstances.
This quick workaround is to actually check for that internal field instead, as it's *only* written in collect_info(), but I think we'll need a better solution in the long term.
Fixes: ea64857890ac6cb8ad056af255cf7b706850bea7 ("feat: Already add package info during crash")
Bug-Ubuntu: https://bugs.launchpad.net/ubuntu/+source/apport/+bug/2038650
=> ui: don't rely on Dependencies to know if collect_info() has been run

data/bash-completion/apport-bug
Users might set aliases for ls breaking the bash completion:
```
alias ls='ls -N --color=yes --time-style=long-iso'
apport-bug <tab>
```
Shellcheck also complains about it:
```
shellcheck -S error -s bash data/bash-completion/{apport-bug,apport-collect,apport-unpack}
In data/bash-completion/apport-bug line 8:
for FILE in $(ls /usr/share/apport/symptoms); do
^-- SC2045 (error): Iterating over ls output is fragile. Use globs.
For more information:
https://www.shellcheck.net/wiki/SC2045 -- Iterating over ls output is fragi...
```
Ubuntu-Bug: https://launchpad.net/bugs/1850804
=> bash-completion: Do not use ls in completion

.github/workflows/ci.yaml, setup.py, setuptools_apport/java.py, tests/run-linters
Replace deprecated distutils by setuptools:
* replace distutils.log by logging library
* drop DistUtilsExtra version check
* port build_java to setuptools
See also https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html
=> setup: replace deprecated distutils by setuptools

apport/hookutils.py, tests/unit/test_hookutils.py
The DMI files `subsystem` and `uevent` will be always skipped. So checking their status with `os.stat` is not needed.
Add a unit test for `apport.hookutils.attach_dmi` that uses real data. This can be used as basis for fixing issues in `attach_hardware` (see https://github.com/canonical/apport/pull/226).
=> hookutils: skip checking stat for skipped DMI files and  add unit test for apport.hookutils.attach_dmi

apport/hookutils.py, tests/integration/test_hookutils.py, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py, tests/unit/test_hookutils.py
Upstart is dead and not used any more. Remove the code for supporting Upstart. For backward compatibility do not remove the function but throw deprecation warnings instead.
=> feat: remove support for Upstart

apport/hookutils.py, tests/unit/test_hookutils.py
Fixes MachineType key to be an f-string instead of a regular string
It looks like when things were changed over to f-strings this one line missed the "f". I did some basic searches through the rest of the code to find other instances of this but couldn't find any.
=> fix: MachineType f-string

.github/workflows/ci.yaml, setup.py
```
$ ./setup.py --help
File "./setup.py", line 106, in <module>
systemd_unit_dir = subprocess.check_output(
File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.10/subprocess.py", line 503, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'
```
=> setup: Do not fail when pkg-config is missing

.github/workflows/ci.yaml
GitHub CI warns: "Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, codecov/codecov-action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."
So upgrade actions/checkout@v3 to actions/checkout@v4.
=> ci: upgrade to actions/checkout@v4

apport/crashdb.py, apport/fileutils.py, apport/packaging_impl/apt_dpkg.py, apport/report.py, apport/ui.py, data/general-hooks/parse_segv.py, problem_report.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/system/test_packaging_apt_dpkg.py
Black merged several multi-line f-strings into one line leaving two f-string in the line that could be merged.
Fixes: 4a38b722974426ba2bd134775358b1d381d17c49 ("Increase maximum line length to 88")
=> style: merge consecutive f-strings

tests/system/test_python_crashes.py
The system tests call `_test_crash` always with `extracode` set and never set `scriptname`. Remove this dead code to increase code coverage.
=> test: remove dead system test code in test_python_crashes

apport/crashdb_impl/launchpad.py
The method `get_id_url` hard-codes the URL to the production Launchpad instance. Use the same logic from `get_comment_url` to correct it.
There are more Launchpad instances besides production, qastaging, and staging. Rely on `launchpadlib.uris.lookup_web_root` to map the short instance names to web root URLs.
Successfully run the Launchpad tests locally:
```
TEST_LAUNCHPAD=1 python3 -m unittest tests/integration/test_crashdb_launchpad.py
```
So the failing codecov/patch can be ignored.
=> Correct get_id_url() for testing Launchpad instances and use launchpadlib.uris.lookup_web_root

tests/integration/test_crashdb_launchpad.py
* Import Report from `apport.report`
* Introduce `_create_bug_from_report()`
* set default description in `_file_bug`
* Also return web_link in `_file_bug`
* pass signal as int to `_generate_sigsegv_report`
* Move more parts into `_generate_sigsegv_report()`
Successfully tested Launchpad tests locally:
```
TEST_LAUNCHPAD=1 python3 -m unittest tests/integration/test_crashdb_launchpad.py
```
So the failing codecov/patch can be ignored.
=> test/launchpad: Some refactorings

data/apport, problem_report.py, tests/integration/test_dupdb_admin.py
`typing.Tuple` is a deprecated alias for `tuple` starting with Python 3.9.
=> replace deprecated typing.Tuple by tuple

apport/report.py, data/apport, tests/unit/test_report.py
Instead of hard-coding only five signal names, determine the signal name using the Python `signal` standard library.
Signal numbers vary by architecture. So include the signal name during crash collection to avoid getting the wrong name when reprocessing on a different architecture.
=> feat: set signal name during crash collection

problem_report.py
Refactor _write_key_and_binary_value_compressed_and_encoded_to_file into a generator taking in all sorts of data and compressing and splitting it into byte chunks, and a function encoding an iterable of binary chunks into an RFC822 base64 field.
The compression generator is still in need of further refactoring, but it's still a step in the right direction.
=> problem_report: separate base64 encoding and gzip compression

apport/report.py, problem_report.py
Add type hints to all methods of `ProblemReport` and `Report` but exclude those methods that needs reworking.
=> feat: Add type hints to ProblemReport and Report

tests/helper.py, tests/integration/test_crashdb_launchpad.py, tests/integration/test_hookutils.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py, tests/unit/test_fileutils.py, tests/unit/test_hooks_image.py, tests/unit/test_hookutils.py, tests/unit/test_packaging_apt_dpkg.py, tests/unit/test_report.py, tests/unit/test_sandboxutils.py, tests/unit/test_signal_crashes.py
Importing `MagicMock` from `unittest.mock` makes the code shorter by reducing the need to wrap long lines.
=> style: Import MagicMock from unittest.mock

apport/ui.py
Simplify the `remember_send_report` code by using `str()` to convert `bool` to `string`.
=> refactor(ui): use str() to convert bool to string

apport/report.py, apport/ui.py, tests/integration/test_report.py
Expect to pass `pid` as `int` to `Report.add_proc_environ`. Add type hints to all callers. Also use `int` in `Report.add_proc_info`, but keep supporting `str` for backward compatibility.
=> Expect to pass pid as int to Report.add_proc_environ

tests/integration/test_ui.py
`pwd.getpwuid` returns a `pwd.struct_passwd`. So let `fake_getpwuid` return the same type.
=> test: let fake_getpwuid return pwd.struct_passwd

problem_report.py
The key and value pairs in Python dicts are called items. So rename the "key and value" part of methods to "item".
Maybe we could drop `_to_file` from the methods to make the function name shorter.
=> problem_report: rename "key and value" to item

.pylintrc, apport/crashdb.py, apport/crashdb_impl/github.py, apport/crashdb_impl/launchpad.py, apport/fileutils.py, apport/hookutils.py, apport/packaging_impl/apt_dpkg.py, apport/report.py, apport/sandboxutils.py, apport/ui.py, bin/apport-cli, bin/apport-retrace, data/apport, data/general-hooks/parse_segv.py, gtk/apport-gtk, kde/apport-kde, problem_report.py, setuptools_apport/java.py, tests/helper.py, tests/integration/test_apport_checkreports.py, tests/integration/test_dupdb_admin.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/integration/test_unkillable_shutdown.py, tests/paths.py, tests/system/test_packaging_apt_dpkg.py, tests/unit/test_fileutils.py, tests/unit/test_problem_report.py
Load more pylint plugins that currently do not complain. This includes useful plugins like `no_self_use`. The `typing` plug-in detects using the deprecated `typing.Tuple`.
=> pylint: load more pylint plugins

apport/report.py
The property `gzipvalue` from `CompressedValue` should not be used directly.
=> report: use isinstance check for CompressedValue

gtk/apport-gtk
`Gtk.Builder.get_object` might return `None`. This should only happen in case `apport-gtk.ui` is broken or not matching. Assert that the widgets are found to detect this kind of issue sooner and to make mypy happy.
=> apport-gtk: assert that widgets are found

bin/apport-cli, gtk/apport-gtk, kde/apport-kde, problem_report.py, tests/integration/test_ui_cli.py, tests/unit/test_problem_report.py
Commit d452b6123689a90433c54cfc96b0bdd07e1c4a83 ("apport-gtk: Show the most interesting fields first in the details view.") implemented showing the most interesting fields only for apport-gtk but ignored apport-cli and apport-kde.
Move the sorting logic into `ProblemReport.sorted_items` and use it in all UI implementations.
=> apport-cli/apport-kde: show the most interesting fields first in the details view

kde/apport-kde, tests/system/test_ui_kde.py
Move setting up `app` from the top-level into `MainUserInterface`. This moves the `app` code to a place where it is tested as well.
`MainUserInterface.ui_question_file` fails:
```python
ERROR: test_ui_question_file_close (tests.system.test_ui_kde.T.test_ui_question_file_close)
File "tests/system/test_ui_kde.py", line 765, in test_ui_question_file_close
self.assertIsNone(self.ui.ui_question_file("Please select a file"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "kde/apport-kde", line 574, in ui_question_file
if response.length() == 0:
^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'length'
```
`QFileDialog.getOpenFileName` returns a tuple of the file name …
=> apport-kde: fix AttributeError in ui_question_file()

apport/ui.py, bin/apport-cli, gtk/apport-gtk, kde/apport-kde, tests/integration/test_ui.py
The parameter `modal_for` in `UserInterface.ui_present_report_details` takes a process ID. Pass the process ID as `int` to it instead of `str` to avoid needing to convert it later.
=> ui: pass PID as int to modal_for in ui_present_report_details

bin/apport-unpack
Move writing each report entry into a separate file to a separate function to make the functions more readable by making them smaller.
=> apport-unpack: introduce unpack_report_to_directory

problem_report.py, tests/integration/test_ui.py
Avoid accessing the `CompressedValue.gzipvalue` property by allowing to set the compressed value on initialization.
This merge request depends on https://github.com/canonical/apport/pull/262.
=> problem_report: support compressed value on CompressedValue init

bin/apport-cli, gtk/apport-gtk, kde/apport-kde
`ProblemReport` tries to convert the values to `str` when reading the report. Only show those string values in the details view instead of converting binary data.
=> ui: only show string values in details view

tests/integration/test_apport_unpack.py
Convert test data for apport-unpack to constants to allow mypy deriving the type.
=> test/apport-unpack: convert test data to constants

gtk/apport-gtk
The variable `have_display` should be a boolean and not a string.
=> apport-gtk: make have_display a boolean

.github/workflows/ci.yaml, doc/data-format.tex, problem_report.py, tests/unit/test_problem_report.py
`systemd-coredump` compresses the coredump with Zstandard. To support copying the coredump into a `ProblemReport` add support for reading Zstandard compressed values.
This merge request contains:
* https://github.com/canonical/apport/pull/255
* https://github.com/canonical/apport/pull/258
* https://github.com/canonical/apport/pull/259
* https://github.com/canonical/apport/pull/260
* https://github.com/canonical/apport/pull/261
* https://github.com/canonical/apport/pull/262
* https://github.com/canonical/apport/pull/269
* https://github.com/canonical/apport/pull/270
=> problem_report: support reading zstd compressed values

.github/workflows/ci.yaml, gtk/apport-gtk, kde/apport-kde, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py
`UserInterface.ui_run_terminal` should only be called after checking that `UserInterface.ui_has_terminal` returns `True`. So assert that `UserInterface.ui_run_terminal` finds a terminal to make mypy happy.
Install `xterm` as terminal application in system-tests, but do not install any terminal application in system-tests-installed to cover not having a terminal application.
=> apport-gtk/apport-kde: assert that terminal was found

.github/workflows/ci.yaml
Ubuntu 23.04 "Lunar Lobster" is end-of-life.
=> ci: drop Ubuntu 23.04 "Lunar Lobster"

.github/workflows/ci.yaml
The unit tests take only a few seconds to run (excluding the setup phase) and their environment is very similar to the integration tests. Combine the unit tests with the integration tests to reduce the number of checks to run and to save container setup cost.
=> ci: combine unit and integration tests

tests/run-linters
Instead of checking each script individually with mypy, call mypy with `--scripts-are-modules` to check all scripts at once. The script `data/apport` needs to be checked separately, because the derived module name `apport` will shadow the `apport` module.
=> run-linters: check scripts with mypy's --scripts-are-modules

apport/report.py, apport/ui.py, tests/integration/test_report.py, tests/integration/test_ui.py
Ubuntu >= 22.04 uses only cgroup2 (Ubuntu 20.04 used both and Ubuntu 18.04 only cgroup version 1). `Report.get_logind_session` will fail to determine the logind session and always return `None` if only cgroup2 is used.
`get_logind_session` searches for cgroup lines with "name=systemd:" and then extracts the session from "/session-". This worked in Ubuntu 16.04 but started to fail in Ubuntu 18.04.
Content of `/proc/self/cgroup` on Ubuntu 16.04 (xenial):
```
12:cpuset:/
11:perf_event:/
10:pids:/user.slice/user-1000.slice
9:blkio:/
8:hugetlb:/
7:net_cls,net_prio:/
6:cpu,cpuacct:/
5:devices:/user.slice
4:freezer:/
3:rdma:/
2:memory:/
1:name=systemd:/user.slice/user-1000.slice/session-c1.scope
```
Content of `/proc/self/cgroup` on Ubuntu 18.04 (bionic):
```
12:freezer:/
11:net_cls,net_prio:/ …
```
=> ui: remove skipping crashes that happened during logout

tests/integration/test_hookutils.py
The test case `test_recent_syslog_overflow` fails on Ubuntu 24.04 (noble) ppc64el on 2024-01-07:
```
=================================== FAILURES ===================================
________________________ T.test_recent_syslog_overflow _________________________
self = <tests.integration.test_hookutils.T testMethod=test_recent_syslog_overflow>
def test_recent_syslog_overflow(self):
"""recent_syslog on a huge file"""
log = os.path.join(self.workdir, "syslog")
with open(log, "w", encoding="utf-8") as f:
lines = 1000000
while lines >= 0:
f.write("Apr 20 11:30:00 komputer kernel: bogus message\n")
lines -= 1
mem_before = self._get_mem_usage()
data = apport.hookutils.recent_syslog(re.compile("kernel"), path=log)
mem_after = self._get_mem_usage()
delta_kb = mem_after - mem_before …
```
=> test: improve debugging failed test_recent_syslog_overflow

.github/workflows/ci.yaml
In addition to the usual statement coverage, also collect branch coverage measurement to ensure that those code path are also tested.
=> ci: also measure branch coverage

setup.cfg, setuptools_apport/java.py
In order to compile with default Java 21 we need to use release 8 instead of 7. 
To avoid changing java compilation class in the future it would be better to make it the minimum java release customisable via a command line option. 
This PR implements `--minimum-java-release=` command line argument for the build command.
With Java 11+ we should be using --release option rather than -source/-target to avoid spurious runtime-related errors. We should fix it as a separate PR after this one.
=> add --minimum-java-release option to the build command

tests/integration/test_hooks.py, tests/integration/test_signal_crashes.py, tests/unit/test_parse_segv.py
There are three cases where the branch coverage report is not stable between runs.
=> test: make branch coverage report stable

bin/apport-retrace
A small amount of refactoring in apport-retrace to understand the provenance of `crashid` and make it clear for both tooling and readers that it has a valid value when trying to push the retrace out to the servers.
Depends on #296 to make mypy happy.
=> Rework apport-retrace to handle unbound crashid (LP: #2051512)

tests/unit/test_hookutils.py, tests/unit/test_problem_report.py
This MR addresses the following test failures caused by the daylight savings:
```
=================================== FAILURES ===================================
______________ TestHookutils.test_attach_journal_errors_with_date ______________
self = <tests.unit.test_hookutils.TestHookutils testMethod=test_attach_journal_errors_with_date>
run_mock = <MagicMock name='run' id='140704711544272'>
@unittest.mock.patch("subprocess.run")
@unittest.mock.patch("os.path.exists", unittest.mock.MagicMock(return_value=True))
def test_attach_journal_errors_with_date(self, run_mock):
run_mock.return_value = subprocess.CompletedProcess(
args=None, returncode=0, stdout=b"journalctl output", stderr=b""
)
report = apport.Report(date="Wed May 18 18:31:08 2022")
apport.hookutils.attach_journal_errors(report) …
```
=> test: do not use hardcoded dates in tests

apport/crashdb_impl/launchpad.py, problem_report.py, tests/integration/test_problem_report.py
Those objects are technically file-like objects, with the associated semantics. In particular, starting with Python 3.12 the class using internal buffering, which means write() calls won't necessarily directly be reflected in the underlying storage object.
For the sake of consistency, the context manager approach has been generalized to read() calls as well, except when we could get away with removing the use of GzipFile altogether.
=> fix: use context manager when manipulating GzipFiles (LP: #2051512)

apport/ui.py
The `run_symptoms` method uses the two lists `symptom_names` and `symptom_descriptions`. Both need to be kept in sync.
Simplify the code by using only one list containing tuples of the symptom description and name. This allows sorting the list without additional list operations. A list is used instead of an ordered dictionary because `ui_question_choice` returns an index.
=> refactor(ui): simplify symptoms handling in run_symptoms

tests/integration/test_signal_crashes.py
To increase the code coverage add a test for
`/proc/sys/fs/suid_dumpable` set to 1 ("debug") and crashing a set-user-ID (suid) program.
=> test: add test_crash_suid_dumpable_debug

data/apport, tests/integration/test_signal_crashes.py
In case the process is running a set-user-ID program, the UID in the report filename will be 0 (UID of root).
Correct the filename to use the UID of the real user. systemd-coredump is doing the same for their core filenames.
This merge request depends on https://github.com/canonical/apport/pull/286.
=> apport: fix UID in report filename for suid programs

apport/packaging_impl/apt_dpkg.py
It's rather costly, shelling out to dpkg and all.
This had the consequence of having to rename the `cache` variable into `apt_cache`, but it might be for the better anyway as there are already other caches around.
=> dpkg: memoize the get_system_architecture method

apport/ui.py, tests/unit/test_ui.py
The `new` parameter in `webbrowser.open` takes an integer and not a boolean: "If `new` is 0, the url is opened in the same browser window if possible. If `new` is 1, a new browser window is opened if possible. If `new` is 2, a new browser page (“tab”) is opened if possible."
run_as_real_user uses `subprocess.run` and `webbrowser.open` which are non-blocking. So forking can be dropped.
`webbrowser.open` returns a boolean. If openining a browser fails (e. g. in a minimal chroot), `webbrowser.open` will return `False`. In this case `UserInterface.open_url` silently does nothing. Print/show an error message in case `webbrowser.open` returns `False`.
=> ui: Drop forking in open_url and show error message if webbrowser.open() fails

apport/crashdb_impl/debian.py, apport/crashdb_impl/github.py, apport/fileutils.py, apport/hookutils.py, apport/report.py, apport/ui.py, bin/apport-cli, data/apport, data/unkillable_shutdown, gtk/apport-gtk, kde/apport-kde, problem_report.py, pyproject.toml, setuptools_apport/java.py, tests/helper.py, tests/integration/test_apport_checkreports.py, tests/integration/test_crashdb_launchpad.py, tests/integration/test_dupdb_admin.py, tests/integration/test_python_crashes.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/integration/test_unkillable_shutdown.py, tests/paths.py, tests/run-linters, tests/unit/test_report.py
Debian testing ships black 24.2.0-1. Modify `tests/run-linters` to skip the black check if black < 24 is installed.
=> chore: Format Python code with black 24.2

.github/workflows/ci.yaml, tests/integration/test_packaging_apt_dpkg.py
The libc-bin package suggests `manpages` on Ubuntu, but recommends it on Debian. If the recommended packages are not installed, the test `test_get_dependencies_depends_only` will fail on Debian:
```
_____________________ T.test_get_dependencies_depends_only _____________________
self = <tests.integration.test_packaging_apt_dpkg.T testMethod=test_get_dependencies_depends_only>
def test_get_dependencies_depends_only(self):
"""get_dependencies() on package with Depends only."""
d = impl.get_dependencies("libc-bin")
self.assertGreaterEqual(len(d), 1)
for dep in d:
>           self.assertTrue(impl.get_version(dep))
tests/integration/test_packaging_apt_dpkg.py:114:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = …
```
=> ci: run integration tests also on Debian

tests/integration/test_signal_crashes.py
test_crash_apport_from_systemd_coredump fails if the current day of the month contains only one digit:
```
>       self.assertEqual(dict(report), dict(expected_report))
E       AssertionError: {'Pro[16 chars]h', 'Architecture': 'amd64', 'Date': 'Wed Apr [4740 chars]'no'} != {'Pro[16 chars]h', 'Date': 'Wed Apr 03 15:32:15 2024', 'ProcC[4740 chars]'no'}
E         {'Architecture': 'amd64',
E       -  'Date': 'Wed Apr  3 15:32:15 2024',
E       ?                   ^
E
E       +  'Date': 'Wed Apr 03 15:32:15 2024',
E       ?                   ^
E
```
=> test: fix date in test_crash_apport_from_systemd_coredump

tests/integration/test_packaging_apt_dpkg.py, tests/system/test_apport_valgrind.py
bash 5.2.21-2ubuntu2 in Ubuntu 24.04 (noble) moves the files to /usr. This causes `test_get_file_package` and `test_get_files` to fail:
```
=================================== FAILURES ===================================
___________________________ T.test_get_file_package ____________________________
self = <tests.integration.test_packaging_apt_dpkg.T testMethod=test_get_file_package>
def test_get_file_package(self):
"""get_file_package() on installed files."""
> self.assertEqual(impl.get_file_package("/bin/bash"), "bash")
E AssertionError: None != 'bash'
tests/integration/test_packaging_apt_dpkg.py:158: AssertionError
_______________________________ T.test_get_files _______________________________
self = <tests.integration.test_packaging_apt_dpkg.T testMethod=test_get_files>
def …
```
=> test: fix integration tests for bash >= 5.2.21-2ubuntu2 and coreutils >= 9.4-3ubuntu1

apport/report.py, tests/integration/test_report.py
Apport 2.28.0 failed to create a crash report from an crash inside a lxc container:
```
File "/usr/share/apport/apport", line 1244, in <module>
sys.exit(main(sys.argv[1:]))
^^^^^^^^^^^^^^^^^^
File "/usr/share/apport/apport", line 761, in main
return process_crash_from_systemd_coredump(options.systemd_coredump_instance)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/apport/apport", line 1240, in process_crash_from_systemd_coredump
return process_crash(report, real_user, report_owner)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/apport/apport", line 1135, in process_crash
info.add_user_info()
File "/usr/lib/python3/dist-packages/apport/report.py", line 554, in add_user_info
user = …
```
=> report: Fix crash if the user is a dynamic user

.github/workflows/ci.yaml
GitHub CI warns: "Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, codecov/codecov-action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."
So upgrade codecov/codecov-action@v3 to codecov/codecov-action@v4. Explicitly set `SKIP_ONLINE_TESTS=1` for the skip tests, because installing ca-certificates causes the skip tests to have their Internet check succeed.
=> ci: upgrade to codecov/codecov-action@v4

apport/packaging_impl/apt_dpkg.py, tests/unit/test_packaging_apt_dpkg.py
The default `/etc/apt/sources.list.d/ubuntu.sources` in Ubuntu 24.04 starts with a comment section:
```
Types: deb
URIs: http://archive.ubuntu.com/ubuntu/
Suites: noble noble-updates noble-backports
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
Types: deb
URIs: http://security.ubuntu.com/ubuntu/
Suites: noble-security
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```
This causes `TestApportValgrind.test_sandbox_cache_options` to fail:
```
File "/__w/apport/apport/bin/apport-valgrind", line 159, in <module>
sandbox, cache, outdated_msg = apport.sandboxutils.make_sandbox(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> apt_dpkg: fix reading comment only entries in APT deb822 sources

tests/integration/test_ui.py
pytest shows following warning when run as root:
```
tests/integration/test_ui.py::T::test_run_report_bug_noperm_pid
/usr/lib/python3/dist-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function UserInterfaceMock.__del__ at 0x7f15bed0d4e0>
File "/__w/apport/apport/tests/integration/test_ui.py", line 111, in __del__
self.crashdb_conf.close()
File "/usr/lib/python3.11/tempfile.py", line 648, in close
self._closer.close()
File "/usr/lib/python3.11/tempfile.py", line 585, in close
unlink(self.name)
PermissionError: [Errno 1] Operation not permitted: '/tmp/tmpunnl4xag'
warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```
This failure is caused by `setUp` calling `self.ui = UserInterfaceMock()` …
=> test: fix deletion of the tmpdir in test_run_report_bug_noperm_pid

tests/integration/test_crashdb_launchpad.py, tests/integration/test_problem_report.py
mypy 1.9.0 complains:
```
tests/integration/test_problem_report.py:539: error: Argument 1 to "write" of "BufferedWriter" has incompatible type "Message | bytes | Any"; expected "Buffer"  [arg-type]
tests/integration/test_crashdb_launchpad.py:759: error: Item "Message" of "Message | bytes | Any" has no attribute "decode"  [union-attr]
Found 2 errors in 2 files (checked 85 source files)
```
The changes to `tests/integration/test_problem_report.py` were tested on my machine:
```
TEST_LAUNCHPAD=1 pytest tests/integration/test_crashdb_launchpad.py
```
=> tests: fix mypy 1.9.0 complains

.github/workflows/ci.yaml
Add Ubuntu 24.04 LTS "Noble Numbat" to the CI. Ubuntu 24.04 is using deb822 sources in `/etc/apt/sources.list.d/ubuntu.sources`.
=> ci: Add Ubuntu 24.04 LTS "Noble Numbat"

apport/report.py, problem_report.py, tests/unit/test_report.py
If a systemd-coredump report points to a coredump file that does not exist (any more), Apport will fail:
```
File "/usr/share/apport/apport", line 1244, in <module>
sys.exit(main(sys.argv[1:]))
^^^^^^^^^^^^^^^^^^
File "/usr/share/apport/apport", line 761, in main
return process_crash_from_systemd_coredump(options.systemd_coredump_instance)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/apport/apport", line 1240, in process_crash_from_systemd_coredump
return process_crash(report, real_user, report_owner)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/apport/apport", line 1146, in process_crash
info.write(reportfile)
File "/usr/lib/python3/dist-packages/problem_report.py", line 548, in write …
```
=> report: Ignore missing COREDUMP_FILENAME

apport/report.py, tests/unit/test_report.py
When running `ubuntu-bug thunderbird` on a system with the thunderbird snap installed, it collects information correctly and opens a page like https://bugs.launchpad.net/distros/+filebug/a9564134-dfa6-11ee-85a7-c7116d9f638e which is not valid.
The snap contact information contains `distros` in the Launchpad URL:
```
$ snap info thunderbird | grep ^contact
contact:   https://launchpad.net/distros/ubuntu/+source/thunderbird
```
Bug-Ubuntu: https://launchpad.net/bugs/2056758
=> report: fix determining bug report URL for Thunderbird

.github/workflows/ci.yaml, setup.py
On /usr merged systems like Ubuntu 24.04 the udev rules are placed into `/usr/lib/udev/rules.d` instead of `/lib/udev/rules.d`.
Determine the location of the udev directory from the pkg-config file and fallback to the old location on failure. Install `pkg-config` in the `system-installed` test.
=> setup: determine udev directory dynamically

tests/unit/test_report.py
`Report._get_ignore_dom()` calls `os.geteuid()` instead of `os.getuid()`.
Fix `test_missing_uid` to mock `os.geteuid` instead of `os.getuid`, use `MagicMock`, and check that the mock was called.
=> test: fix test_missing_uid

data/apport, tests/unit/test_signal_crashes.py
systemd-coredump stores crashes that happen inside a container on the host in case it cannot forward the crash to the container. Apport cannot do anything useful with these crash reports, because the information about the crashed process does not contain the process number seen from inside the container and because the crashed process is already gone when Apport gets the crash from systemd-coredump.
So let Apport just ignore crash reports from systemd-coredump if the crashes happened inside containers.
Bug-Ubuntu: https://launchpad.net/bugs/2063349
=> apport: Ignore container crash reports from systemd-coredump

apport/crashdb_impl/launchpad.py
The chunk size in `HTTPSProgressConnection.send` starts with 1024. The chunk size is checked for being bigger than 1024 before increasing or decreasing it. Therefore this condition will never met and the chunk size will stay at 1024.
Only check for the chunk size to be bigger than 1024 before decreasing it (not before increasing it).
I ran the integration tests locally, but `HTTPSProgressConnection` is not covered by it:
```
TEST_LAUNCHPAD=1 pytest -ra --cov=. --cov-report=html --cov-branch tests/integration/test_crashdb_launchpad.py
```
=> launchpad: fix dynamic adaption of chunck size

apport/report.py
In `Report._gen_stacktrace_top` `fn` might be set to `None` and calling `fn.startswith` will fail in that case.
=> report: Fix possible None.startswith() call

apport/ui.py
Coverity 2023.9.2 rule COV_PY_FORWARD_NULL_PYTHON complains about accessing a property of null-like value "cmd". Refactor the code to satisfy Coverity.
=> ui: refactor suppress evaluation in parse_argv

apport/crashdb.py, tests/unit/test_crashdb.py
Coverity 2023.9.2 rule COV_PY_COPY_PASTE_ERROR_PYTHON complains about `real_fixed_version` in `CrashDatabase.duplicate_db_fixed` looks like a copy-paste error.
For the "crash got reopened" case, `real_fixed_version` is `None` and therefore the call to `duplicate_db_fixed` sets the fixed version back to 'still unfixed'. Make that code more readable by explicitly passing `None` to `duplicate_db_fixed`.
=> crashdb: make _duplicate_db_sync_status more readable

apport/sandboxutils.py, tests/unit/test_sandboxutils.py
On Ubuntu 24.04 (noble):
```
$ divide-by-zero
$ mkdir -p "$PWD/sandbox-config/Ubuntu 24.04"
$ echo noble > "$PWD/sandbox-config/Ubuntu 24.04/codename"
$ cat > "$PWD/sandbox-config/Ubuntu 24.04/sources.list" <<EOF
deb http://de.archive.ubuntu.com/ubuntu/ noble main universe
deb-src http://de.archive.ubuntu.com/ubuntu/ noble main universe
EOF
$ apport-retrace -v -S "$PWD/sandbox-config" --gdb-sandbox -C "$PWD/sandbox-cache" /var/crash/_usr_bin_divide-by-zero.1000.crash
[...]
Extracting downloaded debs...
ERROR: [Errno 2] No such file or directory: '/tmp/apport_sandbox_8x704zqr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2'
```
Bug-Ubuntu: https://launchpad.net/bugs/2067120
=> apport-retrace: install base-files first

apport/report.py, bin/apport-retrace, tests/unit/test_report.py
pylint 3.2.2 complains:
```
************* Module apport-retrace
bin/apport-retrace:515:27: E0601: Using variable 'gdb_sandbox' before assignment (used-before-assignment)
************* Module apport.report
apport/report.py:878:71: E0606: Possibly using variable 'core' before assignment (possibly-used-before-assignment)
```
If `options.gdb_sandbox` evaluates to True, the architecture is the system architecture, and `sandbox` evaluates to False, `gdb_sandbox` will not be set.
The case in `apport/report.py` can be hit by analyzing a local kernel crash report with apport-retrace. `load_report` in `apport-retrace` loads the report with `binary="compressed"`. This leads to `VmCore` being an instance of `CompressedValue` which does not have a `find` method.
Use the high-level interface …
=> pylint 3.2.2 fixes: initialize gdb_sandbox and fix UnboundLocalError in add_kernel_crash_info

tests/paths.py
The argument types should be as generic as possible, but the return types should be as specific as possible.
=> test: make return types more precise

tests/integration/test_apport_checkreports.py, tests/integration/test_hooks.py, tests/integration/test_unkillable_shutdown.py
`subprocess.run` takes a list of strings. So convert `pathlib.Path` to `str` before.
=> test: pass list of string to subprocess

pyproject.toml, tests/run-linters
Move mypy configuration to `pyproject.toml` to support using those setting when called manually.
=> test: move mypy config to pyproject.toml

.github/workflows/ci.yaml
Uploading the code coverage result to Codecov might fail. Then the whole tests needs to be restarted just to try the upload again.
Move uploading the code coverage results to the separate `upload-to-codecov` job. Store the coverage results of the test jobs as artifacts.
=> ci: move upload to Codecov to separate job

apport/packaging_impl/apt_dpkg.py, tests/integration/test_packaging_apt_dpkg.py, tests/unit/test_packaging_apt_dpkg.py
`apport-retrace` shows following warning on Ubuntu 24.04 (noble):
```
WARNING: /lib/x86_64-linux-gnu/libc.so.6 is needed, but cannot be mapped to a package
```
This is caused by libc6 shipping the file in `/usr/lib/x86_64-linux-gnu/libc.so.6`.
=> apt_dpkg: fix finding source for /lib/x86_64-linux-gnu/libc.so.6

.github/workflows/ci.yaml
Ubuntu 23.10 "Mantic Minotaur" will be end-of-life on 2024-07-11.
=> ci: drop Ubuntu 23.10 "Mantic Minotaur"

tests/unit/test_hookutils.py
```
error: Argument "args" to "CompletedProcess" has incompatible type "None"; expected "str | bytes | PathLike[str] | PathLike[bytes] | Sequence[str | bytes | PathLike[str] | PathLike[bytes]]"  [arg-type]
```
Since `subprocess.CompletedProcess.args` is not used by the tests use `MagicMock` to make mypy happy.
=> test: Use MagicMock for subprocess.CompletedProcess.args

data/apport
In case `/var/crash` exists, let `apport --start` not modify the permission of the directory. Otherwise the permission might be changed to an unwanted mode (see discussion in the linked bug).
Create `/var/crash` with mode 3777 instead of 1777 to have the `setgid` permission set. The `setgid` permission causes crash files created in `/var/crash` to inherit its group ownership.
Bug: https://launchpad.net/bugs/2066995
=> apport: create /var/crash with setgid permission

data/whoopsie-upload-all
`apport-autoreport.service` fails if auto-reporting is disabled:
```
$ systemctl status apport-autoreport.service
× apport-autoreport.service - Process error reports when automatic reporting is enabled
Loaded: loaded (/usr/lib/systemd/system/apport-autoreport.service; static)
Active: failed (Result: exit-code) since Thu 2024-06-13 21:55:08 CEST; 1h 9min ago
TriggeredBy: ● apport-autoreport.timer
● apport-autoreport.path
Process: 1059564 ExecStart=/usr/share/apport/whoopsie-upload-all --timeout 20 (code=exited, status=1/FAILURE)
Main PID: 1059564 (code=exited, status=1/FAILURE)
CPU: 86ms
Jun 13 21:55:08 host systemd[1]: Starting apport-autoreport.service - Process error reports when automatic reporting is enabled...
Jun 13 21:55:08 host whoopsie-upload-all[1059564]: ERROR: whoopsie.path is …
```
=> whoopsie-upload-all: exit with 0 if whoopsie is disabled

tests/unit/test_report.py
```
tests/unit/test_report.py:445: error: Item "None" of "str | None" has no attribute "startswith"  [union-attr]
tests/unit/test_report.py:446: error: Item "None" of "str | None" has no attribute "endswith"  [union-attr]
```
=> test: assert that title is not None

tests/unit/test_problem_report.py
```
tests/unit/test_problem_report.py:79: error: Value of type variable "_S" of "assertAlmostEqual" of "TestCase" cannot be "float | int | None"  [type-var]
tests/unit/test_problem_report.py:84: error: Value of type variable "_S" of "assertAlmostEqual" of "TestCase" cannot be "int | None"  [type-var]
```
=> test: assert that get_timestamp() is not None

bin/apport-retrace, tests/paths.py, tests/unit/test_apport_retrace.py
Exit `apport-retrace` with return code 2 in case the report is malformed and with return code 3 on known errors. Crashes of `apport-retrace` will exit with return code 1.
=> apport-retrace: exit without 0 on error

tests/integration/test_recoverable_problem.py
The method `_wait_for_report` initiales `seconds` as `int` but later uses `float` for it. So initialize `seconds` with a `float`.
=> test: use float for seconds variable

tests/integration/test_apport_checkreports.py, tests/integration/test_apport_unpack.py, tests/integration/test_apport_valgrind.py, tests/integration/test_crash_digger.py, tests/integration/test_crashdb_launchpad.py, tests/integration/test_dupdb_admin.py, tests/integration/test_fileutils.py, tests/integration/test_github.py, tests/integration/test_helper.py, tests/integration/test_hooks.py, tests/integration/test_hookutils.py, tests/integration/test_java_crashes.py, tests/integration/test_packaging.py, tests/integration/test_packaging_apt_dpkg.py, tests/integration/test_packaging_rpm.py, tests/integration/test_problem_report.py, tests/integration/test_python_crashes.py, tests/integration/test_recoverable_problem.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/integration/test_ui_cli.py, tests/integration/test_unkillable_shutdown.py, tests/integration/test_whoopsie_upload_all.py
Add type hints to the integration tests where mypy will be happy about. Leave the problematic integration tests untoched for a later point in time.
=> test: add type hints to unproblematic integration tests

tests/system/test_signal_crashes.py
The helper function `pidof` expects the program name to be a string, but `wait_for_no_instance_running` might get passed a `pathlib.Path` as program.
=> test: pass program as string to pidof()

tests/integration/test_ui.py
`UserInterface.format_filesize` takes the size as `int`, but `2.7 * 1000000` is a float.
=> test: pass ints to UserInterface.format_filesize

tests/helper.py, tests/integration/test_helper.py, tests/integration/test_ui.py, tests/system/test_signal_crashes.py
Rename the function `pidof` to `pids_of` to reflect that it will return a set of process IDs. This was requested in https://github.com/canonical/apport/pull/358#discussion_r1679388131.
=> test: rename pidof to pids_of

tests/system/test_python_crashes.py
```
tests/system/test_python_crashes.py:226: error: Argument 2 to "assertIn" of "TestCase" has incompatible type "str | None"; expected "Iterable[Any] | Container[Any]"  [arg-type]
```
=> test: assert that crash_signature() is not None

tests/system/test_packaging_apt_dpkg.py
```
tests/system/test_packaging_apt_dpkg.py:490: error: Argument 2 to "set" of "Configuration" has incompatible type "str | None"; expected "str"  [arg-type]
```
`apt_pkg.config.get` will return an empty string in case the config is not set. So it is safe to let the `get` method return an empty string as fallback value.
=> test: ensure orig_apt_proxy is always a string

tests/system/test_ui_gtk.py
```
tests/system/test_ui_gtk.py:838: error: Argument 2 to "assertIn" of "TestCase" has incompatible type "None"; expected "Iterable[Any] | Container[Any]"  [arg-type]
tests/system/test_ui_gtk.py:839: error: Argument 2 to "assertIn" of "TestCase" has incompatible type "None"; expected "Iterable[Any] | Container[Any]"  [arg-type]
```
=> test: assert that error_title is not None

tests/integration/test_signal_crashes.py, tests/system/test_apport_valgrind.py, tests/system/test_github_query.py, tests/system/test_packaging_apt_dpkg.py, tests/system/test_python_crashes.py, tests/system/test_signal_crashes.py, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py
Fix mypy:
* test: delete variables instead of assigning None
* test: assert that stdin and stderr are not None
Then add type hints to all unproblematic system tests.
=> test: add type hints to unproblematic system tests

tests/system/test_apport_retrace.py
The apport-retrace system tests will write hundreds of megabytes to `module_workdir`. `/tmp` might be on tmpfs and run out of memory when `module_workdir` is placed there.
So put the `module_workdir` into `/var/tmp` to avoid placing those files into memory.
Bug-Ubuntu: https://launchpad.net/bugs/2069815
=> test: put apport-retrace temp files into /var/tmp

tests/system/test_apport_retrace.py
There are a few assumptions made by the test code that only are true on amd64 :)
See https://bugs.launchpad.net/ubuntu/+source/apport/+bug/2069815
Note that we'll probably want to install gdb-multiarch in debian/tests/control in the packaging.
=> Fix retrace tests on non-amd64 (FR-8039)

apport/packaging_impl/apt_dpkg.py, tests/system/test_apport_retrace.py
Move calculating the APT cache root directory into a separate helper method to make it usable by the system tests.
The APT cache directory is different in case the retrace is done for a foreign architecture. So calculate the expected APT cache directory dynamically.
Bug-Ubuntu: https://launchpad.net/bugs/2069815
=> test: fix _assert_cache_has_content checks on non-amd64

apport/crashdb_impl/launchpad.py, tests/unit/test_crashdb_launchpad.py
Just because a report is marked as LaunchpadPrivate and has an actual
architecture attached to it doesn't mean it should be retraced. A
contrario, any report that is designated as LaunchpadPrivate should be
marked as private, even if get_os_info() was never called on it.
Fixes https://bugs.launchpad.net/ubuntu/+source/apport/+bug/2068933
The review will be much easier if done commit-wise.
=> launchpad: don't systematically order retrace on private reports (FR-7945)

apport/fileutils.py, apport/packaging.py, apport/packaging_impl/apt_dpkg.py, apport/packaging_impl/rpm.py, tests/integration/test_packaging.py, tests/integration/test_packaging_apt_dpkg.py, tests/system/test_packaging_apt_dpkg.py
Add type hints to most methods of `PackageInfo` and its subclasses.
The method `_search_contents` is only called by `get_file_package` and `get_file_package` requires the `file` parameter to be of type `str`. Otherwise the `uninstalled=False` case would fail.
So drop supporting `bytes` in `_search_contents`.
=> packaging: add type hints and drop support for file parameter in bytes type

.github/workflows/ci.yaml
Having the same linters run on multiple configurations is IMHO a waste of resources, for gains that have been thus far theoretical, and with actual costs due to discrepancies in the analysis for the various versions.
=> CI: only run the linters on a single configuration

apport/packaging.py, apport/packaging_impl/apt_dpkg.py, apport/report.py, tests/system/test_apport_retrace.py
This contains a small fix as well as a workaround for the underlying issue (which is that GDB can't cope with divide-by-zero on s390x)
=> "Fix" the apport-retrace tests on s390x

apport/hookutils.py, tests/unit/test_hookutils.py
The recent_syslog integration tests were failing autopkgtest due to getting an empty string for the syslog. This was caused by the syslog command finishing before the python code entered the poll loop in `__filter_re_process` and also not checking that the buffer was empty on completion (LP:[#2073935](https://pad.lv/2073935)).
Originally this bug was reported against s390x since it reproduced often there, but there's nothing architecture specific about the issue (other than the process scheduling it seems). For completeness, you can reproduce the output with the following code:
```python
from subprocess import Popen, PIPE
import time
with Popen(["echo", "content"], stdout=PIPE) as p:
time.sleep(1)
pre_complete_content = ""
post_complete_content = ""
while p.poll() is None:
for line in …
```
=> recent-syslog: read stdout after process completion

tests/integration/test_signal_crashes.py
- `wait_for_gdb_child_process` is used exclusively with the sleep command. Rename to `wait_for_gdb_sleeping_child_process` to make the context of function clearer.
- Modify the wait_for_gdb_sleeping_child_process utility function to make sure to wait until the test process is actually sleeping. The expected behavior is that the process has already entered the "sleeping" state when returning from this function. Some callers use this function to generate a process and then examine the stack
trace at a certain state. However, there are steps between "tracing-stop" and "sleeping", such as "running", that may cause the stack trace from the inspected process to look slightly different when compared a stack trace from when the process once has entered the "sleeping" state. This can be seen on …
=> test: wait_for_gdb_sleeping_child_process

.github/workflows/ci.yaml, tests/helper.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/system/test_signal_crashes.py, tests/unit/test_helper.py
- Introduce `wait_for_sleep_cmd` test utility function to wait for a sleep command process to enter the "sleeping" state.
- Make the `create_test_process` helper functions use  `wait_for_sleep_cmd` when invoked with no arguments (the default is test executable is the sleep command) to ensure the process has entered the "sleeping" state before returning.
- Manually call this utility in `test_crash_system_slice` since it calls sleep in a more roundabout fashion via `systemd-run`. This fixes LP: [#2076186](https://bugs.launchpad.net/ubuntu/+source/apport/+bug/2076186), where armhf autopkgtests were failing due to looking for the `sleep` process before it had fully entered the "sleeping" state.
- Add a dependency on `python3-psutil` in the github CI workflow. This will also require the …
=> tests: fix flaky tests waiting for sleep command

po/en_CA.po, po/fi.po
Import translation updates from
https://translations.launchpad.net/ubuntu/noble/+source/apport for languages that have updates. Do not update translations that have no changes except for updated metadata (POT-Creation-Date, X-Launchpad-Export-Date, and X-Generator). Do not import languages that have zero translated messages.
=> feat: Import translation updates from Ubuntu 24.04 (noble)

apport/packaging_impl/apt_dpkg.py, tests/system/test_apport_retrace.py, tests/unit/test_packaging_apt_dpkg.py
The Ubuntu archive is split. The primary mirrors only has packages for the amd64 and i386 architectures. The ports mirrors host all remaining architectures.
So introduce a mapping function that correctly changes the URL in case known problematic ones were found.
=> apt_dpkg: Map mirror to correct URL for the architecture

data/package_hook, tests/integration/test_hooks.py
package_hook can fail on distribution upgrades where the package in question has been removed from the newer release:
```
$ /usr/share/apport/package_hook -p mime-support --tags dist-upgrade [...]
File "/usr/share/apport/package_hook", line 95, in <module>
main()
File "/usr/share/apport/package_hook", line 71, in main
report["SourcePackage"] = apport.packaging.get_source(options.package)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/apport/packaging_impl/apt_dpkg.py", line 308, in get_source
raise ValueError(f"package {package} does not exist")
ValueError: package mime-support does not exist
```
`__AptDpkgPackageInfo.get_source` will raise `ValueError` in case the package is not installed and not found in the APT cache …
=> package_hook: Handle failures of removed packages

apport/report.py, tests/unit/test_report.py
`/etc/apport/report-ignore/README` contains comments. Users or maintainers might want to add comments to their denylist files.
Support comments by ignoring lines starting with `#`.
See https://github.com/canonical/apport/pull/394 for a use case.
=> report: Support comments in denylist files

etc/apport/report-ignore/ignore-teamviewer
Teamviewer ships its own libicudata.so which does not have a `.text` section ([gdb crashes with "internal-error: sect_index_text not initialized" when .text missing](https://sourceware.org/bugzilla/show_bug.cgi?id=25678)). Whenever apport tries to create a coredump for a Teamviewer crash, it triggers a [crash in GDB](https://bugs.launchpad.net/ubuntu/+source/gdb/+bug/2041830). This change prevents apport from creating a report for a Teamviewer crash.
=> apport: Add Teamviewer to report-ignore

apport/REThread.py
Canceling the upload of problem information after sending information acquired with `ubuntu-bug [package name]` causes the upload dialog to become unresponsive.
The main thread is terminated when cancelling the crash collection/uploading, but the spawned background thread will continue running.
Mark the spawned background threads as daemon threads. This will stop those threads when the main tread terminates.
Bug-Ubuntu: https://launchpad.net/bugs/1537310
=> Fix hang when cancelling/closing Apport

gtk/apport-gtk
`on_progress_window_close_event` is connected to those four objects:
* GtkWindow delete-event (window_information_collection)
* GtkButton clicked (button_cancel_collecting)
* GtkWindow delete-event (window_report_upload)
* GtkButton clicked (button_cancel_upload)
`GtkWindow::delete-event` takes an event parameter, but `GtkButton::clicked` does not.
Commit c997c1b12ec6 ("Add type hints to UserInterface class") released in apport 2.30.0 dropped support for not providing `event` when calling `on_progress_window_close_event`.
Fixes: c997c1b12ec6 ("Add type hints to UserInterface class")
LP: #2080524
=> apport-gtk: Fix TypeError on dialog close

bin/apport-cli
apport-cli uses the same character for the No and the Cancel option in the Italien translation:
```
Cosa fare? Le opzioni sono:
Y: Yes
N: No
N: Annulla
Scegliere (Y/N/N):
```
Translate all the answers to allow picking different characters.
Bug-Ubuntu: https://launchpad.net/bugs/2084650
=> apport-cli: translate the answers Yes and No

tests/integration/test_problem_report.py
The test case `test_write_file` fails on s390x from time to time due to the encoded chunks have a different on-disk representation. Instead of the expected one compressed chunk
```
File: base64
H4sICAAAAAAC/0ZpbGUA
c3RyxIAMcBAFAK/2p9MfAAAA
```
there could be two compressed chunks:
```
File: base64
H4sICAAAAAAC/0ZpbGUA
cnTChAxwEA==
BRgAr/an0x8AAAA=
```
The raw data is identical, but the zlib compressed data on disk differs! So make the test case less picky by just checking that the data is compressed and that the decompressed data is correct.
Bug: https://launchpad.net/bugs/2076269
=> test: do not check for exact encoded gzip data in test_write_file

.github/workflows/ci.yaml
Ubuntu 24.04 "noble" is the latest Ubuntu LTS version and the GitHub-hosted runners support it.
=> ci: run installed tests on Ubuntu 24.04

.github/workflows/ci.yaml, apport/packaging_impl/apt_dpkg.py, apport/ui.py, pyproject.toml, tests/integration/test_packaging_apt_dpkg.py, tests/system/test_packaging_apt_dpkg.py, tests/unit/test_packaging_apt_dpkg.py, tests/unit/test_ui.py
Ubuntu 24.04 "noble" is the latest Ubuntu LTS version.
Debian 12 "Bookworm" ships Python 3.11 and Ubuntu 24.04 "noble" ships Python 3.12. So bump the baseline after dropping Ubuntu 22.04 "jammy".
=> ci: Drop testing Ubuntu 22.04 "jammy" and increase required Python version to at least 3.11

.github/workflows/ci.yaml, apport/com.ubuntu.apport.policy.in, tests/integration/test_xml.py
The `/usr/share/polkit-1/actions/com.ubuntu.apport.policy` PolicyKit actions file does not validate against the provided `/usr/share/polkit-1/policyconfig-1.dtd`:
```
$ xmllint --noout --nonet --dtdvalid /usr/share/polkit-1/policyconfig-1.dtd /usr/share/polkit-1/actions/com.ubuntu.apport.policy
/usr/share/polkit-1/actions/com.ubuntu.apport.policy:10: element action: validity error : Element action content does not follow the DTD, expecting (vendor? , vendor_url? , description+ , message+ , icon_name? , defaults , annotate*), got (description message annotate defaults )
/usr/share/polkit-1/actions/com.ubuntu.apport.policy:22: element action: validity error : Element action content does not follow the DTD, expecting (vendor? , vendor_url? , description+ , message+ , icon_name? , defaults , …
```
=> com.ubuntu.apport.policy: fix order of entries

.github/workflows/ci.yaml
Ubuntu 25.04 "Plucky Puffin" is the current development series.
=> ci: add Ubuntu 25.04 "Plucky Puffin"

data/apport, data/gcc_ice_hook, tests/integration/test_signal_crashes.py, tests/system/test_signal_crashes.py
Drop obsolete pylint workarounds that pylint 3.2.7 on Ubuntu 24.10 "oracular" does not complain about any more.
=> chore: drop obsolete pylint workarounds

tests/integration/test_hookutils.py
To increase code coverage, test collecting binary data in `attach_root_command_outputs`.
=> test: test binary data in attach_root_command_outputs

apport/hookutils.py, tests/integration/test_hookutils.py, tests/unit/test_hookutils.py
This should reduce the number of `pkexec` calls to 1 for this function, no matter the branching.
=> hookutils.attach_mac_events pkexec refactoring

po/be.po, po/he.po, po/oc.po
Import translation updates from https://translations.launchpad.net/ubuntu/noble/+source/apport and https://translations.launchpad.net/ubuntu/oracular/+source/apport for languages that have updates. Do not update translations that have no changes except for updated metadata (POT-Creation-Date, X-Launchpad-Export-Date, and X-Generator). Do not import languages that have zero translated messages.
=> po: Import translation updates from Ubuntu 24.04 (noble) and Ubuntu 24.10 (oracular)

apport/ui.py
mypy 1.14.1 complains:
```
apport/ui.py:531: error: Argument 2 to "ui_error_message" of "UserInterface" has incompatible type "str | None"; expected "str"  [arg-type]
apport/ui.py:1833: error: Argument 2 to "ui_error_message" of "UserInterface" has incompatible type "str | None"; expected "str"  [arg-type]
```
Convert `error.strerror` to string in case it is `None`.
=> ui: fix passing possible None to ui_error_message

tests/integration/test_python_crashes.py
Python 3.13 changes the format of the tracebacks. `test_getcwd_error` will cause this traceback:
```
File "/var/tmp/./tmpom46qzi6", line 14, in <module>
os.getcwd()
~~~~~~~~~^^
FileNotFoundError: [Errno 2] No such file or directory
```
So check for `os.getcwd()` and `FileNotFoundError` in the traceback separately.
=> test: fix expected traceback for Python 3.13

apport/ui.py
```
$ apport-cli -c /var/crash/_usr_bin_gnome-shell.1000.crash
File "/usr/bin/apport-cli", line 420, in <module>
if not app.run_argv():
^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/apport/ui.py", line 925, in run_argv
self.run_crash(self.args.crash_file)
File "/usr/lib/python3/dist-packages/apport/ui.py", line 464, in run_crash
response = self.ui_present_report_details(allowed_to_report)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/apport-cli", line 218, in ui_present_report_details
_("&Send report (%s)") % self.format_filesize(self.get_complete_size())
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/apport/ui.py", line 1236, in get_complete_size
if self.report[k]:
~~~~~~~~~~~^^^
File …
```
=> ui: skip value not empty check in get_complete_size

apport/crashdb_impl/github.py, tests/integration/test_github.py
The integration tests for `CrashDatabase.upload` pass a dictionary as report instead of a `ProblemReport` or `Report` object. Relax the input type to a `Mapping`
=> github: relax report parameter type for upload() to a Mapping

bin/apport-cli, problem_report.py, tests/integration/test_ui_cli.py
* problem_report: reuse `self[key]` in `sorted_items` (for the following commits)
* apport-cli: only calculate length for strings to show
* problem_report: sorted_items can also return `CompressedFile`
* Add a type alias for the value type of the `ProblemReport` class.
=> problem_report: introduce ProblemReportValue type alias

apport/crashdb_impl/launchpad.py, tests/unit/test_crashdb_launchpad.py
The Python email library explicitly says both its default and legacy policies do not follow the RFC:
> The default is \n because that’s the internal end-of-line discipline
> used by Python, though \r\n is required by the RFCs.
This is why we cannot have nice things.
It was fine until Launchpad updated its multipart implementation, which became stricter when parsing input. They've temporarily reverted the update, since it broke our error reporting, but we're the ones in the wrong.
Now, there's the bigger question of whether it's appropriate to use the email module to construct a fairly standard HTTP request, and thus bake some obscure knowledge of the HTTP protocol into our code.
The requests library would have given us the needed APIs to generate a multipart/form-data message, but we've …
=> launchpad: force CRLF as HTTP line separators

apport/packaging_impl/apt_dpkg.py
When we set the architecture for our faked chroot, we need to unset foreign architectures as well, otherwise wew end up fetching e.g. i386 packages from ports.
=> Clear APT::Architectures when setting architecture

apport/hookutils.py, problem_report.py, tests/integration/test_apport_unpack.py, tests/integration/test_hooks.py, tests/integration/test_report.py, tests/run-linters, tests/unit/test_problem_report.py
Ubuntu 25.04 (plucky) ships black 25.1.0-1. So use black >= 25 for formatting.
Note: black 24.2 would change `apport/hookutils.py` back.
=> Format code with black 25

apport/crashdb_impl/launchpad.py, tests/unit/test_crashdb_launchpad.py
It turns out that Launchpad itself isn't ready to cope with CRLF line endings.
Fixes: d27a3c68ac "launchpad: force CRLF as HTTP line separators"
Bug-Ubuntu: https://bugs.launchpad.net/launchpad/+bug/2097168
=> Sort of revert the HTTP 1.1 CRLF business

apport/report.py, apport_python_hook.py, data/apportcheckresume, data/java_uncaught_exception, data/recoverable_problem, data/unkillable_shutdown, tests/integration/test_report.py, tests/integration/test_ui.py
* test: use `tempfile.TemporaryDirectory` in `test_add_proc_info`
* unkillable_shutdown: pass `pid` around as `int`
* Add type hints to all callers of `Report.add_proc_info`
* report: expect `pid` parameter of `add_proc_info` to be of type int
=> Expect pid parameter of Report.add_proc_info to be of type int

tests/integration/test_signal_crashes.py
The test `test_unpackaged_script` is skipped, because `do_crash` does not support relative executable path any more:
```
SKIPPED [1] tests/integration/test_signal_crashes.py:382: ./myscript is not executable
```
Determine absolute path for `os.access` and `read_shebang` in `do_crash` when `cwd` is specified.
Also add a commit for using pathlib.
Fixes: 7ae2c0b541a9 ("tests: Convert signal crashes tests into integration tests")
=> test: support relative path in do_crash

tests/integration/test_crashdb_launchpad.py, tests/integration/test_packaging_apt_dpkg.py, tests/integration/test_ui.py
Use `unittest.mock.patch.object` for mocking methods in the test cases to make mypy happy.
=> test: use unittest.mock.patch for mocking methods

.github/workflows/ci.yaml, apport/ui.py, gtk/apport-gtk, tests/helper.py, tests/integration/test_ui_gtk.py
apport-gtk might crash when the desktop environment crashes itself. This kind of crash used to be reproducible by killing gnome-shell (`killall -11 gnome-shell`), but I fail to reproduce it now. The crash can be artificially created:
```
WAYLAND_DISPLAY=bogus DISPLAY=:42 /usr/share/apport/apport-gtk
```
Tested on Ubuntu 25.04 (plucky) on 2025-02-18.
Check for available display on startup. Install gir1.2-gtk-3.0, gir1.2-wnck-3.0, and python3-gi for the new integration test.
Bug-Ubuntu: https://launchpad.net/bugs/2006981
=> apport-gtk: check for available display on startup

.github/workflows/ci.yaml, kde/apport-kde, tests/integration/test_ui_kde.py, tests/system/test_ui_kde.py
apport-kde refuses to launch on a Kubuntu 24.04 (noble) Wayland session (where `WAYLAND_DISPLAY` is set):
```
$ env -u DISPLAY ubuntu-bug
ERROR: This program needs a running X session. Please see "man apport-cli" for a command line version of Apport.
```
apport-kde starts succeesful if only `WAYLAND_DISPLAY` is set. So relax the display server check to the same as apport-gtk.
=> apport-kde: support launching on Wayland

apport/fileutils.py, tests/integration/test_fileutils.py
The function `make_report_file` should only call `os.geteuid()` in case `uid` is not given. It also does this call for `uid = 0`.
=> fileutils: avoid geteuid call in make_report_file for uid=0

apport/fileutils.py, tests/integration/test_fileutils.py
mypy would complain:
```
apport/fileutils.py:602: error: Incompatible types in assignment (expression has type "str", variable has type "int | None")  [assignment]
apport/fileutils.py:603: error: Incompatible types in assignment (expression has type "str", variable has type "int | None")  [assignment]
```
Fix that and add type hints to most of the functions in `apport.fileutils`.
=> fileutils: refactor core_name in get_core_path and add type hints

.github/workflows/ci.yaml, tests/integration/test_fileutils.py
Split `test_find_package_desktopfile` into multiple separate test cases (plus some refactorings, see individual commits).
The test case `test_find_package_desktopfile_multiple` can fail when gnome-terminal is installed. The logic in
`_packages_with_desktop_files` treats following files from gnome-terminal as .desktop files:
* /usr/share/applications/org.gnome.Terminal.Preferences.desktop
* /usr/share/applications/org.gnome.Terminal.desktop
* /usr/share/xdg-terminals/org.gnome.Terminal.desktop
`_packages_with_desktop_files` should ignore files in `/usr/share/xdg-terminals`. Use a regular expression to ignore all
`.desktop` files outside `/usr/share/applications`.
=> test: some refactoring and fix test_find_package_desktopfile_multiple

apport/packaging_impl/apt_dpkg.py
The method `__AptDpkgPackageInfo.install_packages()` has a too high complexity. Carve out various helper methods to reduce the McCabe rating from 89 to 54.
=> Split __AptDpkgPackageInfo.install_packages() into smaller methods

tests/run-linters
The Ubuntu package ships package hooks in `debian/package-hooks`. Check Python code in the `debian` directory if this directory exists.
=> run-linters: check Python code in debian/ if present

.github/workflows/ci.yaml, apport/report.py, tests/integration/test_report.py
Printing `__glib_assert_msg` with GDB on Ubuntu 24.04 (noble) fails:
```
(gdb) print __glib_assert_msg
'__glib_assert_msg' has unknown type; cast it to its declared type
```
So cast `__glib_assert_msg` to `char*` and revive the `test_add_gdb_info_abort_glib` test case.
`extra_gcc_args` in `_generate_sigsegv_report` must be placed last because the glib linker flags must be last.
=> report: fix extracting glib assertion from crashdump

tests/integration/test_problem_report.py, tests/unit/test_problem_report.py, tests/unit/test_report.py
The test cases `test_modify`, `test_write_file`, and `test_report_from_systemd_coredump_storage_journal` fail on s390x from time to time due to the encoded chunks have a different on-disk representation. Instead of the expected one compressed chunk
```
File: base64
H4sICAAAAAAC/0ZpbGUA
c3RyxIAMcBAFAK/2p9MfAAAA
```
there could be two compressed chunks:
```
File: base64
H4sICAAAAAAC/0ZpbGUA
cnTChAxwEA==
BRgAr/an0x8AAAA=
```
The raw data is identical, but the zlib compressed data on disk differs! So make the test case less picky by just checking that the data is compressed and that the decompressed data is correct.
Bug: https://launchpad.net/bugs/2076269
=> test: do not check for exact encoded gzip data

.github/workflows/ci.yaml, apport/crashdb_impl/launchpad.py, apport/report.py, apport_python_hook.py, data/general-hooks/parse_segv.py, pyproject.toml, tests/unit/test_rethread.py
ruff check complains:
```
apport/crashdb_impl/launchpad.py:1063:16: E713 [*] Test for membership should be `not in`
|
1061 |           team = self.options.get("triaging_team", "ubuntu-crashes-universe")
1062 |           person = f"{self.launchpad._root_uri}~{team}"
1063 |           if not person.replace(str(self.launchpad._root_uri), "").strip("~") in [
|  ________________^
1064 | |             str(sub).split("/", maxsplit=1)[-1] for sub in bug.subscriptions
1065 | |         ]:
| |_________^ E713
1066 |               bug.subscribe(person=person)
|
= help: Convert to `not in`
apport/report.py:1616:20: E713 [*] Test for membership should be `not in`
|
1614 |         """
1615 |         if "ExecutablePath" not in self:
1616 |             if not self["ProblemType"] in {"KernelCrash", …
```
=> Fix ruff complains and add ruff check to CI

tests/integration/test_fileutils.py, tests/system/test_packaging_apt_dpkg.py
`ruff format` found consecutive string literals that could be combined.
=> test: concatenate string literals

problem_report.py, tests/integration/test_problem_report.py
Use a consistant chunk size of 128 kB (instead of 1 MB) which is also the maximum block size of Zstandard (`ZSTD_BLOCKSIZE_MAX`).
=> problem_report: reduce chunk size from 1 MB to 128 kB

tests/integration/test_github.py, tests/integration/test_problem_report.py
In case of failures `TestCase.assertTrue` will only tell that the value is not True. Replace `assertTrue` by `assertEqual` or `assertIn` to get better failure messages. Following snippet was used to find the instances:
```
git grep assertTrue | grep ==
```
=> test: replace assertTrue by more specific assert checks

apport/report.py, tests/integration/test_report.py
libnih upstream is dead since 2012-ish and the Debian package is orphaned since 2016 [1]. The libnih package was removed from Ubuntu in 2022. So drop support for libnih.
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1013225
Note: This change should land in Ubuntu 25.10 since we passed the feature freeze of Ubuntu 25.04.
=> report: drop support for libnih

apport/crashdb.py
The Python module `sqlite3` is part of the Python standard library and not naming it `dbapi2` makes the code more readable.
=> crashdb: Import sqlite3 without giving it a different name

tests/system/test_ui_gtk.py
Add type hints to `has_click_event_connected`. A forward reference is needed to avoid the "skip" CI tests fail:
```
==================================== ERRORS ====================================
_________________ ERROR collecting tests/system/test_ui_gtk.py _________________
tests/system/test_ui_gtk.py:56: in <module>
class T(unittest.TestCase):  # pylint: disable=too-many-public-methods
tests/system/test_ui_gtk.py:1213: in T
def has_click_event_connected(widget: Gtk.Widget) -> None:
E   NameError: name 'Gtk' is not defined
```
=> test: add type hints to has_click_event_connected

apport/crashdb.py, apport/crashdb_impl/github.py, apport/crashdb_impl/launchpad.py, apport/crashdb_impl/memory.py, tests/run-linters, tests/unit/test_crashdb.py
Add type hints to apport.crashdb except for functions/methods that involve `Report` since that would lead to cyclic imports:
```
Traceback:
apport/__init__.py:8: in <module>
from apport.report import Report
apport/report.py:50: in <module>
from apport.ui import HookUI, NoninteractiveHookUI
apport/ui.py:49: in <module>
import apport.crashdb
apport/crashdb.py:27: in <module>
from apport.report import Report
E   ImportError: cannot import name 'Report' from partially initialized module 'apport.report' (most likely due to a circular import) (apport/report.py)
```
There are preparation commits to fix mypy issues beforehand.
=> crashdb: deduplicate code in duplicate_db_publish and add type hints

.github/workflows/ci.yaml, pyproject.toml
To avoid needing to specify `--cov-branch` on the pytest calls, set the branch code coverage in `pyproject.toml`.
=> test: set branch code coverage in pyproject.toml

bin/apport-retrace, bin/apport-valgrind
Remove unused import of apport.fileutils. No idea why no linter complained about that.
=> Remove unused import apport.fileutils

apport/__init__.py
For faster module loading defer the imports needed for the deprecated and hopefully unused `unicode_gettext`.
=> apport: defer imports for unicode_gettext

bin/apport-retrace, bin/apport-unpack, bin/apport-valgrind, bin/crash-digger, bin/dupdb-admin, data/gcc_ice_hook, data/iwlwifi_error_dump, data/kernel_crashdump, data/package_hook, data/unkillable_shutdown, gtk/apport-gtk
Use `apport.logging` instead of using the logging functions imported via the `apport` base module. This step is done as preparation for deprecation (to speed up the `apport` module loading).
=> use apport.logging directly

apport/report.py
The method `Report.crash_signature` has a too high complexity. Split this method into multiple private methods.
=> report: split crash_signature into multiple methods

apport/__init__.py, tests/unit/test_deprecation.py
Deprecate using the logging functions directly from the base `apport` module. Users should import the logging functions from `apport.logging` instead.
=> Deprecate logging functions in base apport module

tests/integration/test_signal_crashes.py
Calling `data/apport` via `subprocess.check_call` will not be covered by coverage. Call into the `data/apport` code directly to get it covered.
pytest will fail with PermissionError and INTERNALERROR on cleanup when running all integration tests as root. So keep using `subprocess.check_call` for tests that set a different UID.
=> test: increase code coverage for data/apport

.github/workflows/ci.yaml
This does not *completely* work around GHA's line buffering, but at least now when a test is hanging we have a better chance of knowing in which module that test is.
=> ci: run the tests in verbose mode

setup.cfg, setuptools_apport/java.py
We're the sole users of that plugin so the migration is fairly easy, and setuptools has apparently deprecated (and actually broken) the use of kebab-case option names in setup.cfg, see
https://github.com/pypa/setuptools/blob/main/NEWS.rst#v7800
=> setuptools/java: use snakecase for option name

data/apport
Crashes in the Chrome snap can crash Apport:
```
File "/usr/share/apport/apport", line 1248, in <module>
sys.exit(main(sys.argv[1:]))
^^^^^^^^^^^^^^^^^^
File "/usr/share/apport/apport", line 773, in main
if _check_global_pid_and_forward(options):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/apport/apport", line 732, in _check_global_pid_and_forward
forward_crash_to_container(options)
File "/usr/share/apport/apport", line 531, in forward_crash_to_container
sock_fd = os.open(
^^^^^^^^
ProcessLookupError: [Errno 3] No such process: 'root/run/apport.socket'
```
Example /proc/cmdline:
```
/usr/bin/python3 /usr/share/apport/apport -p1 -s4 -c0 -d1 -P570846 -u1000 -g1000 -- !snap!chromium!2934!usr!lib!chromium-browser!chrome
/usr/bin/python3 …
```
=> apport: catch ProcessLookupError in forward_crash_to_container

apport/report.py, tests/integration/test_signal_crashes.py, tests/unit/test_report.py
Include the ELF package metadata from systemd-coredump in the crash report. This information can be used later to check if the ELF package metadata matches the installed packages.
=> Include ELF package metadata from systemd-coredump

apport/hookutils.py, data/apport
To make pyright and pylint happy, assert that stdout/stderr from `subprocess.Popen` are not `None` before trying to access them.
=> apport/hookutils: assert that stdout/stderr is present

apport/report.py, tests/integration/test_report.py
Let `_build_proc_maps_cache` return the proc maps cache. The caller in `_address_to_offset` can rely on it being not `None` then.
=> report: let _build_proc_maps_cache return the cache

tests/integration/test_signal_crashes.py
Make sure that `server.close()` is always called after `server.listen(1)`.
=> test: ensure server is always closed in _call_apport_via_socket

tests/integration/test_fileutils.py, tests/unit/test_fileutils.py
The test case `test_get_core_path` fits into the unit test category. So move this test from the integration tests to the unit tests and split the test into individual tests (converting the comments into docstrings).
=> test: move get_core_path tests to unit tests

apport/packaging.py, tests/unit/test_packaging_apt_dpkg.py
`PackageInfo.get_os_version()` uses `lsb_release` as fallback in case `NAME` and/or `VERSION_ID` is not set in `/etc/os-release`. This may only be the case for Debian testing/unstable.
Debian testing/unstable with base-files 13.7 has following `/etc/os-release`:
```
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
`lsb_release -s --release` will return `n/a` in this case and therefore does not provide any benefit.
So drop the `lsb_release` fallback from `PackageInfo.get_os_version()`.
=> packaging: drop lsb_release support from get_os_version()

apport/packaging_impl/apt_dpkg.py
Make Pyright happier about `apt_dpkg` by importing the used modules from `apt` explicitly.
=> apt_dpkg: import used modules explicitly

apport/packaging_impl/apt_dpkg.py
mypy complains about:
```
apport/packaging_impl/apt_dpkg.py:520: error: Missing return statement  [return]
```
=> apt_dpkg: ensure that get_lp_binary_package always return a tuple

apport/packaging_impl/apt_dpkg.py
Check that `pickle.load()` returns a dictionary. Otherwise discard the loaded cache.
=> apt_dpkg: check return type of pickle.load()

apport/packaging_impl/apt_dpkg.py
Query `self._apt_pkg` only once in `_AptDpkgPackageInfo.get_source()`.
=> apt_dpkg: avoid double evaluation in get_source()

apport/packaging_impl/apt_dpkg.py
The type for `_AptDpkgPackageInfo._contents_mapping_obj` is `dict[bytes, bytes]` (or `None`), but it also stores the string mapping for `release` and `arch`.
Make the `_AptDpkgPackageInfo._contents_mapping_obj` dictionary consistent by only inserting `bytes`.
Fixes: 2307e770559b ("packaging: add type hints")
=> apt_dpkg: make type for _contents_mapping_obj consistent

apport/packaging_impl/apt_dpkg.py
Query `self._apt_pkg` only once in
`_AptDpkgPackageInfo.get_architecture()`.
=> apt_dpkg: avoid double evaluation in get_architecture()

apport/packaging_impl/apt_dpkg.py
Split `install_packages` into two methods and address the mypy complains triggered by that.
=> apt_dpkg: split install_packages into two methods

tests/integration/test_crashdb_launchpad.py
gcc will complain:
```
crash.c: In function ‘f’:
crash.c:2:5: error: type of ‘x’ defaults to ‘int’ [-Wimplicit-int]
2 | int f(x) {
|     ^
```
This is equivalent to commit a730657a2f8d
("test/test_report.py: Fix C warnings").
=> test: fix C warning about implicit int

apport/report.py, tests/unit/test_report.py
Use the same library search order from `ld.so`:
```
$ ld.so --help
[...]
Shared library search path:
(libraries located via /etc/ld.so.cache)
/lib/x86_64-linux-gnu (system search path)
/usr/lib/x86_64-linux-gnu (system search path)
/lib (system search path)
/usr/lib (system search path)
```
=> report: use library search order from ld.so

tests/helper.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/integration/test_unkillable_shutdown.py, tests/system/test_packaging_apt_dpkg.py, tests/system/test_signal_crashes.py
Several test cases use the sleep command as test case. Some kill the sleep command while it is sleeping and expect a certain stack trace. So enforce using the GNU coreutils implementation of the sleep command.
Since Ubuntu 25.10 (questing) the GNU implementation is shipped by gnu-coreutils and the commands are prefixed with `gnu`.
Bug-Ubuntu: https://launchpad.net/bugs/2111595
=> test: use cat and sleep from GNU coreutils

.github/workflows/ci.yaml, tests/README.md, tests/run-linters
There is no way for overriding complaints from pyflakes (like unused imports). Drop pyflakes and rely on the other tools (like pylint) instead.
This PR is split from https://github.com/canonical/apport/pull/475 and https://github.com/canonical/apport/pull/477.
=> test: drop running pyflakes

apport/packaging.py, apport/packaging_impl/apt_dpkg.py, apport/packaging_impl/rpm.py, tests/integration/test_fileutils.py, tests/system/test_packaging_apt_dpkg.py
Add type hints to all methods of `PackageInfo` and address mypy's complaints.
=> packaging: add type hints to all PackageInfo methods

apport/fileutils.py, tests/integration/test_fileutils.py
Add type hints to more functions in `apport.fileutils`.
=> fileutils: add more type hints

data/apport
When a low privileged processes crashes, an apport crash report file is written to /var/crash which contains various technical details including the raw base64 encoded core dump. A core file could potentially include sensitive data such as passwords and encryption keys. The issue is the report file has group read permissions by default. If there is no `whoopsie` group, any user that is a member of the same primary group can read the crash reports of another user which could lead to the disclosure of sensitive information.
In case there is no `whoopsie` group, leave the group ownership untouched and rely on the configuration of `/var/crash`. In case whoopsie is not installed, the default for `/var/crash` will be mode 3777 and (group) owned by root.
Bug: https://launchpad.net/bugs/2106338
=> apport: Do not change report group to report owners primary group

problem_report.py
The method `_try_unicode()` is private and only called with values of type `bytes`. So drop supporting `str` there.
=> problem_report: make input type of _try_unicode stricter

data/apport, tests/unit/test_signal_crashes.py
If the binary is in a container, our check will be looking at the binary OUTSIDE that container, which is rather problematic. We take advantage of the /proc/pid/root facility to avoid that.
Bug-Ubuntu: https://bugs.launchpad.net/ubuntu/+source/apport/+bug/2112272
Fixes: a806cac1fa13 ("apport: do consistency check before forwarding crashes")
=> apport: check the exe mtime within the proc root mount (LP: #2112272)

apport/ui.py, tests/unit/test_ui.py
The method `UserInterface.run_hang` requires `pid` to be of type `int`.
=> ui: drop unneeded int conversion in run_hang

apport/packaging_impl/apt_dpkg.py
make_sandbox is the only user. duplicates are not possible there.
=> apt_dpkg: use collections.OrderedDict for packages

apport/crashdb_impl/github.py, apport/crashdb_impl/launchpad.py, apport/sandboxutils.py, apport/ui.py, bin/apport-retrace, bin/apport-valgrind, data/gcc_ice_hook, data/iwlwifi_error_dump, data/kernel_crashdump, data/kernel_oops, data/package_hook, data/unkillable_shutdown, data/whoopsie-upload-all, tests/integration/test_python_crashes.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/system/test_python_crashes.py, tests/system/test_signal_crashes.py, tests/unit/test_hookutils.py
Import `Report` from `apport.report` directly as one step to lazy load the code in `apport/__init__.py` itself (and maybe deprecate it in the future).
=> Import Report from apport.report directly

po/ca.po, po/cs.po, po/da.po, po/en_CA.po, po/en_GB.po, po/hu.po, po/ia.po, po/id.po, po/ko.po, po/my.po, po/tr.po, po/zh_TW.po
Import translation updates from Launchpad for languages that have updates. Do not update translations that have no
changes except for updated metadata (POT-Creation-Date, X-Launchpad-Export-Date, and X-Generator). Do not import languages that have zero translated messages.
=> po: Import translation updates from Ubuntu

apport/report.py, tests/unit/test_report.py
There are several crashes reported on https://errors.ubuntu.com with:
```
File "/usr/share/apport/whoopsie-upload-all", line 246, in <module>
main()
File "/usr/share/apport/whoopsie-upload-all", line 228, in main
stamps = collect_info()
^^^^^^^^^^^^^^
File "/usr/share/apport/whoopsie-upload-all", line 162, in collect_info
res = process_report(r)
^^^^^^^^^^^^^^^^^
File "/usr/share/apport/whoopsie-upload-all", line 112, in process_report
r.add_gdb_info()
File "/usr/lib/python3/dist-packages/apport/report.py", line 1022, in add_gdb_info
addr_signature = self.crash_signature_addresses()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/apport/report.py", line 1761, in crash_signature_addresses
offset = self._address_to_offset(addr) …
```
=> report: check for errors in ProcMaps in crash_signature_addresses

tests/system/test_apport_valgrind.py
Several test cases use the sleep command as test case. Some kill the sleep command while it is sleeping and expect a certain stack trace. So enforce using the GNU coreutils implementation of the sleep command.
Since Ubuntu 25.10 (questing) the GNU implementation is shipped by gnu-coreutils and the commands are prefixed with `gnu`.
Bug-Ubuntu: https://launchpad.net/bugs/2111595
Fixes: 6830e0cbd423 ("test: use cat and sleep from GNU coreutils")
=> test: use true from GNU coreutils
