canonical/apport

tests/helper.py
```
tests/helper.py:40: error: "Callable[[], Any]" has no attribute "cache"
```
Use a LRU cache for `has_internet()` to make the code shorter and easier to read.
=> tests: Use LRU cache for has_internet()

tests/integration/test_signal_crashes.py
The `wait_for_gdb_child_process` helper method can success on the first try. Then the "sleep and retry" part of the function is not used which leads to a reduced code coverage.
Write test cases for the `wait_for_gdb_child_process` helper method to have full code coverage for it.
=> tests: Test wait_for_gdb_child_process() helper method

tests/integration/test_signal_crashes.py
The `wait_for_core_file` helper method can success on the first try. Then the "sleep and retry" part of the function is not used which leads to a reduced code coverage.
Write test cases for the `wait_for_core_file` helper method to have full code coverage for it.
=> test: Test wait_for_core_file() helper method

.github/workflows/ci.yaml
Include `setup.py` calls in code coverage.
=> ci: Include setup.py calls in code coverage

.gitignore
=> chore: Add .coverage to .gitignore

README.md
* Fix filename to commit for release
* Document translation template updates
=> docs(README.md): Fix filename to commit for release and document translation template updates

data/apport
To ease testing:
* Carve `forward_crash_to_container()` out of `main()`
* Pass arguments to `main` function
* Let `main()` return the exit code
=> Refactor data/apport

NEWS.md, apport/ui.py
=> Release apport 2.24.0

tests/system/test_unkillable_shutdown.py
The GitHub CI container do not have systemd and therefore skip the `unkillable_shutdown` system tests. The `system-tests-installed` tests against the install Apport and therefore the coverage is not recorded for the repository path `data/unkillable_shutdown`.
Drop requiring systemd for the `unkillable_shutdown` system tests. Avoid `os.fork`, `os.execv`, or killing the test process runner to allow coverage to cover the process' execution.
=> refactor: Make unkillable_shutdown system tests run in containers

tests/integration/test_ui.py
Convert `_run_test_executable` into a context manager, which takes care of launching and killing the test executable. Avoid `os.fork` and `os.execv` to allow coverage to cover it.
=> refactor(tests): Use context manager for _run_test_executable

NEWS.md, apport/crashdb.py, apport/crashdb_impl/launchpad.py, apport/fileutils.py, apport/packaging.py, apport/sandboxutils.py, bin/apport-retrace, data/apport, tests/unit/test_problem_report.py, tests/unit/test_report.py, tests/unit/test_signal_crashes.py
Use inclusive names:
* Replace dummy by more suitable alternatives
* Rename sanity to consistency
* Rename whitelist to allowlist
* Rename blacklist to ignore
=> Inclusive naming

tests/helper.py, tests/integration/test_apport_checkreports.py, tests/integration/test_hooks.py, tests/integration/test_java_crashes.py, tests/integration/test_recoverable_problem.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui_cli.py, tests/integration/test_unkillable_shutdown.py, tests/integration/test_whoopsie_upload_all.py, tests/paths.py, tests/system/test_signal_crashes.py, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py, tests/system/test_unkillable_shutdown.py, tests/unit/test_hooks_image.py, tests/unit/test_parse_segv.py, tests/unit/test_signal_crashes.py
Use `pathlib` in tests since it is more Pythonic.
=> test: Use pathlib

.github/workflows/ci.yaml
Add Ubuntu 23.04 "Lunar Lobster" to CI.
=> ci: Add Ubuntu 23.04 "Lunar Lobster"

NEWS.md, apport/ui.py
=> Release apport 2.25.0

tests/integration/test_unkillable_shutdown.py
Instead waiting for the test process to appear, communicate the test process ID via a queue. This requires less code.
=> test: Communicate test process ID via a queue

apport/crashdb.py, apport/packaging_impl/apt_dpkg.py, apport/packaging_impl/rpm.py, apport/report.py, apport/ui.py, apport_python_hook.py, bin/dupdb-admin, data/apport, data/apportcheckresume, setup.py, tests/integration/test_signal_crashes.py, tests/unit/test_fileutils.py
Black 23.1 got a little bit more strict and complains about parts where older versions were happy.
=> chore: Format code with black 23.1

NEWS.md, apport/ui.py
=> Release apport 2.26.0

.github/workflows/ci.yaml, tests/integration/test_github.py, tests/system/test_github_query.py
Autopkgtests fail otherwise because they cannot reach Github.
=> fix: Mock query to Github in integration test.

apport/ui.py, tests/integration/test_ui.py
In 2012 commit c178f28c505f1249f525d6441bd21469c810b14b reverted back to calling sudo instead of dropping privileges ourselves due to Launchpad bug #916810.
This behavior of Firefox cannot be reproduced any more. Stop relying on sudo and drop the privileges ourselves. This reduces the dependency on `sudo` and relying on `sudo` to be properly configured.
=> Replace sudo by dropping privileges ourselves

NEWS.md
Add unreleased changes for the upcoming 2.26.1 release to NEWS.md.
=> docs: Add unreleased changes for 2.26.1 to NEWS.md

problem_report.py
Hello,
here is another one. Should be straight forward. 
Something I noticed when looking at this, was that `fileutils` constructs the path name and opens the file. And then the file handle gets passed around. That surprised me a bit , I would have expected something like:
```
my_data = some_function()
my_path = path_creation_function()
with open(my_path) as f:
f.write(my_data)
```
Should that be a todo for the future?
=> refactor: add _write_asc_to_file

tests/integration/test_crashdb_launchpad.py, tests/integration/test_dupdb_admin.py, tests/integration/test_fileutils.py, tests/integration/test_helper.py, tests/integration/test_hookutils.py, tests/integration/test_packaging.py, tests/integration/test_packaging_apt_dpkg.py, tests/integration/test_packaging_rpm.py, tests/integration/test_problem_report.py, tests/integration/test_report.py, tests/integration/test_ui.py, tests/integration/test_whoopsie_upload_all.py, tests/system/test_python_crashes.py, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py, tests/unit/test_crashdb.py, tests/unit/test_fileutils.py, tests/unit/test_parse_segv.py, tests/unit/test_problem_report.py, tests/unit/test_report.py, tests/unit/test_rethread.py
Replace `assertNotEqual(x, None)` by `assertIsNotNone(x)` and `assertEqual(x, None)` by `assertIsNone(x)`.
=> test: Use assertIsNotNone() and assertIsNone()

apport/report.py
Split `Report.standard_title` into smaller methods by introducing `Report._get_python_exception_title` and `Report._get_signal_crash_title`.
=> refactor: Split Report.standard_title into smaller methods

kde/apport-kde, tests/system/test_ui_kde.py
`findChild` returns a `QObject`. Assert that the return type matches the requested size to make mypy happy.
=> apport-kde: assert that findChild() returns correct type

kde/apport-kde, tests/unit/test_problem_report.py
mypy will complain about incompatible types in assignment.
=> avoid reusing variable names

apport/report.py, problem_report.py, tests/unit/test_report.py
There can only be one system core dump handler on a Linux system and Apport is the Ubuntu default core dump handler. Besides Apport other tools offer coredump handler, in particular systemd-coredump. Due to Apport being installed on all Ubuntu system by default none of these alternate system can be installed.
Implement converting a coredump from systemd-coredump into an Apport problem report.
Bug-Ubuntu: https://launchpad.net/bugs/2048136
=> feat: support reading report from systemd-coredump

apport/crashdb.py, apport/logging.py, apport/sandboxutils.py
Here is a grab bag of type hints added while working on #295.
=> Various type hints

apport/packaging_impl/apt_dpkg.py
There are already other caches around in the method, so we might want to use an explicit variable name.
Split off #294
=> apt_dpkg: rename generic 'cache' variable into 'apt_cache'

data/apport, tests/unit/test_signal_crashes.py
These refactoring are preparation work for https://github.com/canonical/apport/pull/290.
=> refactor(apport): split main into smaller parts

tests/unit/test_signal_crashes.py
Extend `test_receive_arguments_via_socket_import_error` to also check the logs.
`builtins.__import__` must not be mocked before `assertLogs` is called. Therefore move mocking `builtins.__import__` into the method as context manager.
=> test: check logs in test_receive_arguments_via_socket_import_error

apport/packaging_impl/apt_dpkg.py, tests/integration/test_packaging_apt_dpkg.py
On systems with DEB822 sources, determining the primary mirror will probably fail when other sources (like PPAs) are added. On my system with DEB822 sources the `test_sandbox_cache_options` test case fails with `urllib.error.HTTPError: HTTP Error 404: Not Found` because it tries to query the PPA as primary Ubuntu mirror:
`https://ppa.launchpadcontent.net/<user>/<ppa>/ubuntu/dists/mantic/Contents-amd64.gz` does not exist.
So check for the `.sources` file named after the distribution (e.g. `ubuntu.sources` for Ubuntu and `debian.sources` for Debian) first for the primary mirror.
=> apt_dpkg: fix heuristic for determining primary mirror with DEB822 sources

apport/packaging_impl/apt_dpkg.py
Split `__AptDpkgPackageInfo._search_contents()` into smaller methods to make the code more readable and modifiable.
I did this refactoring to find the test failure, but then I found the failure elsewhere: https://github.com/canonical/apport/pull/310
=> apt_dpkg: split _search_contents into smaller methods

.github/workflows/ci.yaml
Run pytest with `--durations=0` to see the execution times of the test cases.
=> ci: run pytest with --durations=0

tests/unit/test_crashdb.py
Use `unittest.mock.patch.object` to mock calls to
`Report.crash_signature` and `Report.crash_signature_addresses` instead of manually replacing them.
=> test: properly mock crash_signature* calls

apport/report.py
Introduce the `_get_gdb_path` helper function to reduce the size of `Report.gdb_command`.
=> report: add _get_gdb_path helper function

tests/helper.py, tests/unit/test_crashdb.py, tests/unit/test_fileutils.py, tests/unit/test_helper.py, tests/unit/test_hooks_image.py, tests/unit/test_hookutils.py, tests/unit/test_packaging_apt_dpkg.py, tests/unit/test_packaging_impl.py, tests/unit/test_parse_segv.py, tests/unit/test_problem_report.py, tests/unit/test_report.py, tests/unit/test_rethread.py, tests/unit/test_signal_crashes.py
Add type hints to all unit tests.
=> test: add type hints to unit tests

tests/system/test_apport_retrace.py
The `divide-by-zero` command exits with signal `SIGTRAP` on ppc64el instead of `SIGILL`:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/powerpc64le-linux-gnu/libthread_db.so.1".
Program received signal SIGTRAP, Trace/breakpoint trap.
0x0000000100000880 in ?? ()
Saved corefile /tmp/tmpwpt__shz/divide-by-zero.core
```
So read the signal name from the GDB stdout.
=> test: determine divide-by-zero signal dynamically

setup.py
Follow PEP 561: https://peps.python.org/pep-0561/
=> apport: mark apport with py.typed marker

data/apport, problem_report.py, tests/integration/test_packaging_apt_dpkg.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py, tests/integration/test_ui.py, tests/integration/test_ui_cli.py, tests/integration/test_unkillable_shutdown.py, tests/system/test_signal_crashes.py, tests/system/test_ui_gtk.py, tests/system/test_ui_kde.py, tests/unit/test_crashdb_launchpad.py
=> test: Add more type hints

.github/workflows/ci.yaml, tests/integration/test_signal_crashes.py
... With a sprinkle of refactoring on top.
=> Fix setuid tests due to ping dropping setcap (LP: #2089387)

.github/workflows/ci.yaml, apport/crashdb.py, apport/crashdb_impl/github.py, apport/crashdb_impl/launchpad.py, apport/crashdb_impl/memory.py, apport/packaging.py, apport/packaging_impl/apt_dpkg.py, apport/sandboxutils.py, bin/crash-digger, data/apport, data/iwlwifi_error_dump, data/kernel_crashdump, problem_report.py, pyproject.toml, tests/helper.py, tests/integration/test_signal_crashes.py, tests/integration/test_unkillable_shutdown.py
Address complaints from pylint 3.3.1 and run linter on Ubuntu 25.04 "Plucky Puffin".
=> pylint 3.3.1 adjustments and run linter on Ubuntu 25.04 "Plucky Puffin"

tests/integration/test_hookutils.py
The function `apport.hookutils.attach_root_command_outputs` is not used by Apport itself, but by several hooks. So add a test case for it.
The new test requires `APPORT_DATA_DIR` to be set correctly. Thus `local_test_environment` is used.
=> test: add test case for attach_root_command_outputs

apport/hookutils.py
Very much like attach_root_command_outputs except that it simply stores the outputs in a dict rather than modifying an existing report. Very useful for post-processing.
=> hookutils: new helper execute_multiple_root_commands

apport/hookutils.py, tests/unit/test_hookutils.py
The issue boils down to regexes being tricky.
At least now we have some test coverage for the function :)
=> Fix hookutils.attach_mac_events (LP: #2090887)

tests/integration/test_hookutils.py
Simplify test code by using the `restore_os_environ` context manager.
=> test: use restore_os_environ in hookutils tests

problem_report.py, tests/unit/test_problem_report.py
In problem reports binary data is compressed in chunks of 1 MB. Each compressed chunk is base64 encoded and written as one line in the problem report file. This is the rule for all binary data formats except for `CompressedValue`.
The problem report files are text files. Text editors like gedit might choke on text files that have huge lines. So the problem report should wrap the lines at a reasonable length.
So write `CompressedValue` in chunks as well.
=> problem_report: write CompressedValue in chunks as well

apport/hookutils.py
Improve readability of `read_file`.
=> hookutils: improve readability of read_file

setup.py
We don't need to do that anymore, Python2 is a thing of the past, everyone is on the python3 bandwagon.
=> setup.py: remove the shebang mangling code

tests/integration/test_signal_crashes.py
Refactor the helper function `create_dropsuid` into `compile_c_code` to allow reusing the code for compiling other test executables.
=> test: introduce helper function compile_c_code

tests/integration/test_signal_crashes.py
Some pyright fixes for `test_signal_crashes`.
=> Some pyright fixes for test_signal_crashes

apport/packaging_impl/apt_dpkg.py
Add more type hints to `_AptDpkgPackageInfo`.
=> apt_dpkg: add more type hints

apport/crashdb.py, apport/crashdb_impl/debian.py, apport/crashdb_impl/github.py, apport/crashdb_impl/launchpad.py, apport/crashdb_impl/memory.py, tests/unit/test_crashdb_debian.py
Add type hints to `CrashDatabase.__init__` plus the changes needed to make mypy happy.
=> crashdb: add type hints to CrashDatabase.__init__

tests/integration/test_crashdb_launchpad.py, tests/integration/test_problem_report.py, tests/integration/test_python_crashes.py, tests/integration/test_report.py, tests/integration/test_signal_crashes.py
Add type hints to all integration tests.
=> test: add type hints to integration tests
